### ISSUE TITLE
Draft CG charter template

### ISSUE THREAD

**Issue by prushforth** [w3c/charter-drafts#1]
This repo seems like a good idea.  Is there a template one could use to draft a charter, or other monkey-see monkey-do resources that can be pointed to.

Thanks

**Comment by shepazu** [comment]
@prushforth I just created a first draft of a template. Pull requests or forks welcome!

http://w3c.github.io/charter-drafts/charter-template.html

**Comment by prushforth** [comment]
Perfect, thanks!  Will use that.
