### ISSUE TITLE
Which charter template for CGs?

### ISSUE THREAD

**Issue by koalie** [w3c/charter-drafts#107]
I see from the description here that the charter template is good for WGs and CGs.
However in the [CGs documentation](https://www.w3.org/community/about/good-practice-for-running-a-group/), we suggest people refer and use the [recommended charter template](https://github.com/w3c/cg-charter).

They're not the same. Can we choose one and update our various documentations? #kthx!

**Comment by wseltzer** [comment]
Thanks @koalie. I suggest we point everyone to the same template, the one in charter-drafts.

When someone updates the CG documentation, they might also point out that many groups are using github issues rather than tracker.

**Comment by koalie** [comment]
Having reviewed both templates, my opinion is that a specific CG template continues to make sense. I have therefore proposed #119.
