### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by wseltzer** [w3c/charter-drafts#108]
@plehegar see if https://github.com/w3c/charter-drafts/blob/gh-pages/draft-states.md meets your and team contacts' needs

@caribouW3 I refer to the tool we discussed to help team contacts in identifying the Reference Draft.

**Comment by plehegar** [comment]
Yep, That fits my need

**Comment by caribouW3** [comment]
If I understood correctly, you need the uri of the CR when the latest CfE-triggering document is a CR.
Right? (technically we also call it a RefDraft, but the process definition of Reference Draft is not aligned with the current implementation of the PP)

**Comment by wseltzer** [comment]
Yes, what we need as "Reference Draft" is: latest of CR, WD in (FPWD+90)

**Comment by plehegar** [comment]
I think we dealt with this one. Feel free to reopen if you think otherwise.
