### ISSUE TITLE
Web Assembly WG: charter length should be 2 years

### ISSUE THREAD

**Issue by henceproved** [w3c/charter-drafts#118]
https://w3c.github.io/charter-drafts/webassembly.html

We discussed the Web Assembly WG charter draft internally at Google, and believe the current charter length of 3 years to be too long. In general, we would like to see charters that enable re-evaluation of the WG's deliverables at about the same cadence as spec publication, to allow for expanding scope over time, and for work to move between groups more easily.

We recommend a charter length of either 18 months or 2 years as a more reasonable duration.

@flagxor @sideshowbarker

**Comment by flagxor** [comment]
Sounds fine. I happen to have chatted with Johnny Stenback when he visited the Wasm CG meeting. The CG chair + others seems fine with 2 years (3 was just some arbitrary guess).
Will revise.

**Comment by flagxor** [comment]
Adjusted:
https://github.com/w3c/charter-drafts/commit/a4f9115b94851342ea7acb6ce9041b21c55c26a5
