### ISSUE TITLE
[charter template] Teleconferences

### ISSUE THREAD

**Issue by wseltzer** [w3c/charter-drafts#128]
We've gotten feedback that teleconferences are hard to make globally inclusive because of timezones and language barriers. In addition, more groups are finding github issues and mailing lists more effective for discussion and issue resolution. Groups are free to schedule teleconferences taking these issues into account, but let's remove them from the charter template default.

**Comment by tantek** [comment]
Accepting the concerns noted (timezones etc.), I for one have found that teleconferences in practice have served as a useful regular "push" for productive milestones in WGs, as well as being a point where disparate conversations can be quickly summarized/curated by chairs towards WG consensus, much more so than async methods. I agree there needs to be a good balance of use of async methods (github issues etc.) for gathering broader input / iterating on topics, however telcons seem to be quite effective at getting that last bit of convergence/consensus that async methods can so often passively ignore (or seemingly not consider minority viewpoints).

I'd suggest keeping telcons in the default template for these reasons.
* Useful deadline pressure for productive iteration
* Provides better opportunity to reach consensus on already discussed issues

**Comment by wseltzer** [comment]
Proposal: close as-is. It's useful for groups to have teleconfs, or make a considered case if they want a different workmode.
