### ISSUE TITLE
[charter template] Note: Using the template

### ISSUE THREAD

**Issue by wseltzer** [w3c/charter-drafts#130]
While a charter is being drafted, use [DRAFT]; 
When it is proposed to the Advisory Committee for review, => [PROPOSED], and freeze the text.

Should we then move it to date-space? Alternately, if using github refs, include the last commit ID.

**Comment by koalie** [comment]
I support moving a proposed charter to date-space.

**Comment by wseltzer** [comment]
Thanks @koalie, we'll make that recommended practice.

* Before proposing to the AC, move the PROPOSED charter to w3.org date-space (leaving a pointer to the github repo for continued issue-raising). That way, we can update the draft in response to AC review comments, without changing what's being reviewed.

**Comment by wseltzer** [comment]
Noted in README
