### ISSUE TITLE
[charter template] Privacy and security considerations

### ISSUE THREAD

**Issue by wseltzer** [w3c/charter-drafts#131]
Change the "should" to a must for privacy and security considerations? and for the other success criteria at this point?

**Comment by tantek** [comment]
Possibly as a CR entry requirement?

When a spec explicitly encourages implementations (CR), presumably the spec authors should at least provide an attempt at privacy and security considerations section for those implementations to consider.

**Comment by svgeesus** [comment]
This issue was fully addressed by Sam's PR, so should be closed.
