### ISSUE TITLE
[charter template] decision policy

### ISSUE THREAD

**Issue by wseltzer** [w3c/charter-drafts#132]
Some charters say that consensus on a call or meeting is provisional until confirmed online after publication in meeting minutes. Commenters have suggested that this may not provide enough notice of potential controversial decisions. Should the charter require a work-mode that calls out distinct CfC messages on the mailing list?

**Comment by tantek** [comment]
The opposite, charters should allow for a WG to choose not to use a mailing list for anything formal.

**Comment by svgeesus** [comment]
A cfc need not rely on a mailing list. For example, a GH issue could be used. So if we add language encouraging cfc, we should not specify a particular mechanism (and certainly not encourage mailing lists).

@tantek would that satisfy your concern?

**Comment by svgeesus** [comment]
ping @tantek

**Comment by svgeesus** [comment]
The current charter template has changed meantime and now says, under [Decision policy](https://w3c.github.io/charter-drafts/charter-template.html#decisions) (my bold):

> To afford asynchronous decisions and organizational deliberation, any resolution (including publication decisions) taken in a face-to-face meeting or teleconference will be considered provisional. A call for consensus (CfC) will be issued for all resolutions **(for example, via email and/or web-based survey)**, with a response period from [pick a duration within:] one week to 10 working days, depending on the chair's evaluation of the group consensus on the issue. If no objections are raised _on the mailing list_ by the end of the response period, the resolution will be considered to have consensus as a resolution of the (Working|Interest) Group. 

With the exception of the remaining _on the mailing list_, which I feel can be dropped, this seems to solve this issue
