### ISSUE TITLE
[charter template] note on Scope section

### ISSUE THREAD

**Issue by wseltzer** [w3c/charter-drafts#133]
The scope section has a key function: to guide the WG chairs, participants, and reviewing legal teams on the outer boundaries of their work and patent commitments. To facilitate that review "Scope" should be limited to a clear description of the WG's permitted work areas. Other material (background, explanations, motivations) should go outside the Scope section.

**Comment by svgeesus** [comment]
@wseltzer does your PR fully address this (I think so) and thus, can this issue be closed?
