### ISSUE TITLE
Add code of conduct link to charter template

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/charter-drafts#140]
Code of Conduct should be linked in the Participation section of the Charter template, for avoidance of doubt about what members are signing up to when they join.

**Comment by wseltzer** [comment]
The Code of Conduct is now specified in the Process, https://www.w3.org/2018/Process-20180201/#ParticipationCriteria : "Participants in any W3C activity must abide by the terms and spirit of the W3C Code of Ethics and Professional Conduct." 

Should we duplicate that in charters, for emphasis?

**Comment by nigelmegitt** [comment]
> Should we duplicate that in charters, for emphasis?

I don't think so, no, at least not as a normative statement. It creates a dependency and potential ambiguity if the wording differs between the charter and the Process, either when the charter is approved or later if the Process changes.

It also suggests that some Group might be able to choose a different code of conduct, which is not the intention.

Duplication can, in that sense, weaken the requirement rather than emphasise it. Looking at [TTWG's Charter](https://www.w3.org/2018/05/timed-text-charter.html), there's a helpful statement:

>  In the event of a conflict between this document or the provisions of any charter and the W3C Process, the W3C Process shall take precedence. 

but it's better to avoid the possibility of a conflict in the first place rather than rely on a statement like that.

**Comment by chaals** [comment]
I think duplicating the pointer is fine actually, since it is the Code itself that sets the requirements...

**Comment by nigelmegitt** [comment]
> it is the Code itself that sets the requirements

@chaals Isn't the requirement to work within the Code in the Process?

**Comment by svgeesus** [comment]
[3.1 Individual Participation Criteria](https://www.w3.org/2019/Process-20190301/#ParticipationCriteria):

> Participants in any W3C activity **must** abide by the terms and spirit of the W3C Code of Ethics and Professional Conduct and the participation requirements described in section 6 of the W3C Patent Policy.

**Comment by svgeesus** [comment]
There seems to be consensus that:

- the requirement to follow the CoC is in the Process
- duplicating the text from the Process document is harmful
- adding a link is beneficial

So I'm going to make a PR to the template to add such a link. And as @nigelmegitt suggested, I will make it clear that this is not an optional or customizable requirement.
