### ISSUE TITLE
Implementations of each feature

### ISSUE THREAD

**Issue by tguild** [w3c/charter-drafts#141]
at least two independent implementations</a> of each of feature defined in the specification.

seems a bit off with respect to the wording

better may be:

at least two independent implementations</a> of each of the features defined in the specification.

or as an Auto WG colleague suggested:

at least two independent implementations</a> of every feature defined in the specification.

https://github.com/PatrickCQ/w3c-automotive/commit/3a38061da5ba65cccd9b74ad2a36330103379b42#diff-bccef84f51267971b1b50f25393d1dce

**Comment by marcoscaceres** [comment]
"feature" doesn't really make sense tho, because what's a feature? Specs do define conformance requirements tho, which are concrete things that can be tested and computationally verified.

**Comment by svgeesus** [comment]
I guess the term "feature" comes from the [W3C Process Document, section 6.2.4 Implementation Experience ](https://www.w3.org/2019/Process-20190301/#implementation-experience):

> Implementation experience is required to show that a specification is sufficiently clear, complete, and relevant to market needs, to ensure that independent interoperable implementations of _each feature_ of the specification will be realized.

(there are 17 occurrences of the word `feature` in the current Process Doc.)

I agree with @marcoscaceres that it makes more sense to talk of implementations of each conformance requirement; this is what individual WPT tests actually link to. But that is a wider ranging change than just the charter template; if affects a bunch of other testing documentation and the Process Doc as well.

**Comment by svgeesus** [comment]
In addition, in CR, "features at risk" does not apply at the granularity of an individual conformance statement but instead a group of them (a whole attribute, attribute value, property, property value, API call etc) which thus constitutes a feature (which can be removed in it's entirety if there is insufficient implementation).

But `feature` is poorly defined, I agree.
