### ISSUE TITLE
add history to web apps charter

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#148]
The charter says "The WebApps Working Group was a predecessor to the Web Platform Working Group...".  Given that, there should be some detailed history in section 10.1

**Comment by marcoscaceres** [comment]
I wonder if we should actually reduce this more... The purpose of the charter is for mission, scope, and listing deliverables, and groups we will liaise with (and possibly a few other procedural things) - so feel like history might best be put on the working group's homepage.

**Comment by plehegar** [comment]
(this charter was approved some time ago)
