### ISSUE TITLE
team contact FTEs seems too low

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#152]
https://rawgit.com/w3c/charter-drafts/gh-pages/webapps-2019.html proposes .1 FTE.  Can 17 specs be shepherded in only two days per month?  Will the WG really need that little support?

**Comment by LJWatson** [comment]
The draft WebApps charter is by no means complete yet, hence this and other apparently missing and/or incorrect pieces of information.

**Comment by LJWatson** [comment]
Ping @plehegar
