### ISSUE TITLE
clean up security review requirements

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#153]
resolved by https://github.com/w3c/charter-drafts/pull/149

**Comment by svgeesus** [comment]
This PR was closed unmerged, with the [comment that the changes should really apply to the template](https://github.com/w3c/charter-drafts/pull/149#issuecomment-430574749). Re-tagging accordingly. @samuelweiler could you make a PR on the template to resolve this?

**Comment by samuelweiler** [comment]
This change was made to the template months ago: https://github.com/w3c/charter-drafts/pull/154
