### ISSUE TITLE
WebApps charter: Location of priv//sec/a11y content

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-drafts#160]
>Each specification shall describe, either inline or preferably as a section in the specification:>

If we document this in the charter, my strong preference is for a distinct section in each specification. It makes it much easier for people to find the information they need, and it doesn't preclude information being added inline.

**Comment by LJWatson** [comment]
Ping @marcoscaceres  and @chaals

**Comment by marcoscaceres** [comment]
@LJWatson, yes, that makes sense.
