### ISSUE TITLE
Complex accessibility expectations

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-drafts#169]
>For specifications of technologies that directly impact user experience, such as content technologies, as well as protocols and APIs which impact content:
Each specification should contain a section on accessibility that describes the benefits and impacts, including ways specification features can be used
to address them, and recommendations for maximising accessibility in implementations.>

This is a complicated way to describe this expectation, that will make it harder for chairs and editors to understand what is needed.

Suggest putting accessibility on the same footing as privacy and security, by including it in the following statement:
>Each specification should contain a section detailing all known security, privacy, and accessibility  implications for implementers, Web authors, and end users.>

**Comment by svgeesus** [comment]
When writing charters, I have assumed that the sentence starting "For specifications of technologies" is guidance; so I decide if the charter has any user-facing component and if so, delete it but include the following sentence "Each specification should".

I think the assumption was that anything which does not impact content does not need an accessibility section. For example a more efficient (but still lossless) compression scheme for HTTP would not.

Then again, it would probably not need an internationalization section either.

I tend to agree that the first sentence is not really needed.

**Comment by svgeesus** [comment]
I think this has been fixed meanwhile: the current template says "for all specifications" rather than "each specification". Here is the full paragraph:

> For all specifications, this (Working|Interest) Group will seek horizontal review for accessibility, internationalization, performance, privacy, and security with the relevant Working and Interest Groups, and with the TAG. Invitation for review must be issued during each major standards-track document transition, including FPWD. The (Working|Interest) Group is encouraged to engage collaboratively with the horizontal review groups throughout development of each specification. The (Working|Interest) Group is advised to seek a review at least 3 months before first entering CR and is encouraged to proactively notify the horizontal review groups when major changes occur in a specification following a review.

**Comment by plehegar** [comment]
closing. Feel free to re-open if you believe more needs to be done.
