### ISSUE TITLE
Web apps charter scope

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/charter-drafts#170]
Need to make sure that the charter has enough scope for Web Share, File stuff, and Badging. It might already, but need to check.

**Comment by LJWatson** [comment]
Was wondering which category we should put these specs in, in the carter, but actually wondering if we should just simplify all specs into a single table?

**Comment by marcoscaceres** [comment]
Yes, let's combine into a single table. And then just focus on the scope. I'll send a PR for the scope.

**Comment by marcoscaceres** [comment]
@LJWatson the specs combined into a single table is pull request #172.

**Comment by plehegar** [comment]
(this charter was approved some time ago)
