### ISSUE TITLE
WebApps spec: Strangeness in the Deliverables table

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-drafts#178]
Not sure if this is intentional, but it seems that some strange content has been introduced into the 2.1 Normative specifications table. For example:

* The description for ARIA in HTML now starts with ```<<<<<<< HEAD```
* The description for Clipboard now includes ```=======

Level 1...```
* The description for contentEditable contains ```>>>>>>> 58eadd32d50f35e15a42815964720c25e3887eb6```

It goes on. These additions make it pretty horrible to read with a screen reader, and I imagine without one too. Can we clean this up?

**Comment by ylafon** [comment]
Which version are you looking ?  It looks like a result of a conflict in a merge, but I don't see it in the gh-pages branch.

**Comment by LJWatson** [comment]
Hmm. I had updated my local clone and was looking at that. I've just looked at the [published version](https://w3c.github.io/charter-drafts/webapps-2019.html) though, and it's completely different (even the tables are different), so I'm puzzled...

**Comment by marcoscaceres** [comment]
Checking in the browser, the link above appears to be up to date. Might just be the page is cached?

**Comment by plehegar** [comment]
this charter was approved some time ago
