### ISSUE TITLE
Need to agree which licence to use

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/charter-drafts#18]
We need to decide whether to use the document licence or the software licence for our deliverables. Can be different licences depending on which document, but it's cleaner to just use the same one throughout.

**Comment by palemieux** [comment]
Re: TTWG charter.

I recommend using the W3C Document License (at least for TTML-related work) as it makes it easier for W3C to retain control of the specification, reducing the potential for confusion in the marketplace.

**Comment by nigelmegitt** [comment]
[TTWG Meeting 2016-02-25] Consensus is Document License for IMSC and all TTML derived deliverables.

**Comment by tmichel07** [comment]
I will discuss it with PLH to either:
-  tweek the text to allow both licensing on document basis.
- remove this section.

**Comment by tmichel07** [comment]
IMSC and TTML will use the document licence. Other Documents may use either the document licence or the software and document licence.
