### ISSUE TITLE
[svg-2019][charter template] Sentence fragment

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#184]
The third paragraph of Section "1.1 Success Criteria" of the [svg 2019 charter](https://w3c.github.io/charter-drafts/svg-2019.html) reads:

> Testing plans for each specification, starting from the earliest drafts.

That's not a full sentence.

**Comment by svgeesus** [comment]
Redirecting this issue, as the sentence in question comes from the [W3C charter template](https://github.com/w3c/charter-drafts/blob/gh-pages/charter-template.html#L160)

**Comment by frivoal** [comment]
Well, it's a problem with the template, but also with the shg charter. Should be tagged on both
