### ISSUE TITLE
[svg-2019] Mandatory external incubation?

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#187]
Section "1. Scope" of https://w3c.github.io/charter-drafts/svg-2019.html

Says:
> As a secondary focus, the group may address modules for new graphical features for SVG, once there is broad consensus on adding each such feature to the Web Platform.

That is very reasonable, and I support it.

However, section "3. Coordination" / subsection "3.1 W3C Groups" goes on to say:
> The SVG Working Group will incubate and review new proposals that are within scope of our charter within SVGCG (and also any other fora, such as WICG). Once an incubated proposal is implemented and available in at least one major browser, and has support from one more, it may be adopted by the SVG Working Group.

This forbids the SVG WG from taking on new specs unless they have been "available" in one browser. "available" is not defined, but I suppose it means and will be understood as shipping.
* The SVG-CG's charter is not written
* By and large, CGs (and also any other fora) are not bound by the formal W3C consensus process
* If that first available implementation has non trivial market share (which is by definition the case for a "major browser"), changing any aspect of the design of the feature may prove impractical due to compatibility concerns.

Together, this guts the SVG-WG of it's ability to influence, much less control, the design and details of new features, and renders the W3C process inoperative until it's too late to change much of anything. That's not good.

I suggest deleting this paragraph, and leaving the chairs in charge of deciding how they want to allow incubation and transitions from incubation based on the "once there is broad consensus on adding each such feature to the Web Platform" statement from section 1.

**Comment by AmeliaBR** [comment]
I agree with Florian's concerns about the specific wording.

Based on conversations we've had in the working group, I would expect that the criteria for moving a proposal from the community group to the WG would be more like "has support from" or "has implementation commitments from" at least one major browser, or at least two SVG implementers (not all of whom are browsers).

**Comment by michaelchampion** [comment]
@frivoal wrote
> "available" is not defined, but I suppose it means and will be understood as shipping.

I agree "available" needs to be clarified, but would not understand that to mean "shipping". I would expect to to mean "behind a flag" or "in a prototype/fork/polyfill" or "available to participants in an origin trial" or something.  

This is a challenge that probably doesn't have a clean solution.  Clearly the "waterfall" model of getting consensus on a spec, take it to CR, and then implementers go off and implement it is more or less romantic fiction at this point.  But the alternative of implementers just defining a feature and taking it to the WG to rubber stamp is dystopian fiction (well, so far it's fiction, but it's a dystopia even implementers don't want to live in). I think we'll have to get used to living at the boundary of chaos between these two modes.

I'm not (personally, not speaking for Microsoft here) opposed to leaving this to the chair's discretion, but I think charter language that neither prescribes a rigid process nor simply leaves it up to the chair would be appropriate.  I think the draft language does the job fairly well, but could be clarified (e.g. defining "available" or saying that there should be a WG consensus that the incubation criteria have been met) .

**Comment by frivoal** [comment]
> I think we'll have to get used to living at the boundary of chaos between these two modes.

I agree, which is why I think charters should neither mandate full waterfall nor after-the-fact rubber stamping, and the best is to leave it to the WG and it's chairs, possibly guided by some judicious SHOULDs.

The current phrasing is too far on the "must rubber stamp after the fact" side for my taste.

**Comment by chaals** [comment]
There is also a serious question about what a "major browser" is. It would seem more reasonable to be thinking about tools that are regarded as serious in a relevant field. For example, if the "SVG art world" uses the Wigwam browser heavily, and the meteorology world uses the Bridle browser, then a serious prototype of the feature in those probably makes sense.

The concern about being forced to accept whatever the first adopter chooses is still very serious, and I agree with @frivoal that the current language makes that far too likely.

**Comment by AmeliaBR** [comment]
> The SVG-CG's charter is not written

FYI, here's my initial draft for the SVG community group's charter:
https://github.com/w3c/charter-drafts/pull/197

In the community group scope, I've specifically forbid working on anything that already has _multiple_ shipping non-experimental implementations — at that point, we really want the standard to move over to the full royalty commitments in the WG.  However, I leave it entirely open for a specification to transition over to the WG sooner, subject of course to the WG accepting it.

**Comment by svgeesus** [comment]
The same concern about shipping, and thus too late for changes, was raised during AC review. The charter text [now reads](https://www.w3.org/Graphics/SVG/svg-2019.html#scope):

> Once an incubated proposal is implemented and available (in nightly or testing builds) in at least one major browser, and has support from other SVG implementers, it may be adopted by the SVG Working Group.

**Comment by frivoal** [comment]
That's better.

I still think that's too strict, as it forbids us from starting work under the W3C process, even if all involved would want to, until at least one member has spent enough on implementation that they may now be reluctant to change.

As a "this is typically a good point to start", this wouldn't bother me. As "this is the earliest point at which you can possibly start", I don't like it nearly as much.

**Comment by frivoal** [comment]
For what it's worth, I think the criteria in the SVG-CG is better.

If the SVG-WG, which includes implementers, has a consensus that something should graduate from incubation ('cause they all wanna work on it and think the spec is in a promissing shape), I don't understand what we gain from blocking it.

Given the available resources in the various browsers, the most likely implementer of anything is Google. So we're effectively saying that we cannot start standardization until Google has implemented. Then we'll adopt the document as FPWD, and Google, who has at that point been sitting on their implementation for a while, gets tired of not getting the benefits of the time they've spent implementing, and now ships, since it's on the standards track. Now it's shipping in the dominant browser, so we cannot change it anymore. Not saying this will happen every time, but it seem like the most likely outcome most of the time.

**Comment by samuelweiler** [comment]
It looks like the SVG charter was approved without adopting this proposed change.  :-(  Given that, should this issue be closed?

**Comment by plehegar** [comment]
this charter was approved some time ago
