### ISSUE TITLE
[Devices and Sensors] term defined in external, unstable document

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#193]
Like https://github.com/w3c/charter-drafts/issues/185, the [[DRAFT] Devices and Sensors Working Group Charter](https://www.w3.org/2019/02/DeviceAPICharter-ac.html) has a normative dependency on an external document that can be updated without going through the AC, and charters should have no such things.

The charter says that the group will follow a "test as you commit" approach, but that term is defined elsewhere. How it is defined (such as whether it uses SHOULDs or MUSTs) will impact the work mode of the working group. That should be in-lined in the charter.

**Comment by plehegar** [comment]
See #185 for a proposal.

**Comment by xfq** [comment]
We decided to to link to the testing policy at https://www.w3.org/2019/02/testing-policy.html

(See commit https://github.com/w3c/dap-charter/commit/03613cec4d9ab8d028c584a788321245ace1c0ee)

**Comment by xfq** [comment]
Added a blockquote to be more consistent with the change in the [SVG charter](https://www.w3.org/Graphics/SVG/svg-2019.html): https://github.com/w3c/dap-charter/commit/d00d6dfe1d62da3b09e49f9cc698b71a3e0c37f5

**Comment by xfq** [comment]
Closing.

**Comment by frivoal** [comment]
Linking to a stable document is an improvement, but I don't consider the issue closed: this is a fix, but I don't consider it a very good one.
On the plus side:
* The normative text has been inlined
* The document linked to, which contains normative text, cannot be changed without AC review

On the negative side:
* Redundant normative text is bad practice. If the two are maintained and stay identical, there was no point in having two. If they go out of sync for some reason, it is then unclear how to resolve the conflict.
* Multiple charters normatively linking to a document that can only be updated with an AC review of the charters linking to it makes the document impossible to update, except by forking it, in which case it no longer is a central point of coordination.

I suggest instead:
* Keep the inlined text, and treat it as normative
* link to an **informative** document, probably on /Guide, with information on best practices regarding testing. It may include a quote duplicating the testing policy, as long as this is clearly marked as an informative reminder.
