### ISSUE TITLE
[charter template] Don't link to documents that can change arbitrarily

### ISSUE THREAD

**Issue by koalie** [w3c/charter-drafts#194]
Channeling Florian who recently brought up that issue on a few recent draft charters, exemplified by #185, I'd like section 1.2 of the charter template itself to be updated, so that 

- either we point to the [snapshot version of the testing policy](https://www.w3.org/2019/02/testing-policy.html) instead of the hyperlink to https://github.com/w3c/testing-how-to/#test-as-you-commit (which can be changed without an AC ballot) or 

- we invite in-lining which testing policy the group adopts (as some charters might tweak the text to accommodate different cases.)

**Comment by swickr** [comment]
> * either we point to the [snapshot version of the testing policy](https://www.w3.org/2019/02/testing-policy.html) instead of the hyperlink to https://github.com/w3c/testing-how-to/#test-as-you-commit (which can be changed without an AC ballot) or
> 
> * we invite in-lining which testing policy the group adopts (as some charters might tweak the text to accommodate different cases.)

It has been suggested that we both in-line the three paragraphs of  [testing policy](https://www.w3.org/2019/02/testing-policy.html) _and_ provide a link to allow readers to find more information.  If (as I'd then propose) the link is to  [testing policy](https://www.w3.org/2019/02/testing-policy.html) then that document serves also as a locus for FAQ and change proposals for future versions of a testing policy.
