### ISSUE TITLE
[svgcg-2019] Defining incubation

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/charter-drafts#200]
In the charter for the SVG community group — which is intended to “incubate” specs for the SVG WG, as required in the [WG's new charter](https://www.w3.org/Graphics/SVG/svg-2019.html) — I found my self struggling to define what that means. The following issue is marked in the [draft CG charter](https://w3c.github.io/charter-drafts/svgcg-2019.html#scope-of-work), but I wanted to post it here for wider review:

**Does a standard definition of “incubation” for a specification already exist?** I couldn't find one, but would prefer to link by reference instead of defining this here. Especially with respect to the boundary between incubation and the recommendation-track.

On the mailing list, @frivoal [replied](https://lists.w3.org/Archives/Public/public-svgcg/2019Mar/0003.html):

> I don't think there's one. The topic has been discussed numerous times by numerous people, but there isn't a single authoritative definition that I know of. What you have in the charter seems reasonable.

Which brings up a secondary question: _Should_ there be a standard definition of incubation for specs, or is it okay to keep this as a vague concept defined by individual groups?

For reference, the current definition for incubation that I'm using in [the community group charter](https://w3c.github.io/charter-drafts/svgcg-2019.html#scope-of-work) is:

> Incubate, in the context of a proposed specification, means to:
> 
> - Connect interested stakeholders, including content creators and software implementers
> - Collect use cases, requirements, and related information for defining the scope and purpose of potential features
> - Identify any implementation concerns, including security, privacy, accessibility, and internationalization impacts
> - Draft and refine specification text
> - Gather feedback and track issues and suggestions
> - Develop test cases and other examples of how the specification should be implemented
> - Optionally, build experimental implementations and related software to demonstrate the proposal's potential
> 
> After successful incubation, a proposed specification would be ready for transition to the W3C technical report process (AKA, the “recommendation track”).

__________

FYI, I'll be taking the SVG CG charter to a final vote next week, so any comments before April 11 are appreciated.

**Comment by AmeliaBR** [comment]
On another project, I discovered that WHATWG does have an official [definition of `incubation`](https://whatwg.org/workstream-policy#incubation) in their Workstream Policy:

> "Incubation" means the work of exploring and developing technologies that require additional testing and refinement before browser engine developers can reasonably make a preliminary commitment to implement the technology in publicly distributed browsers.

The suggestion that incubation is what happens _before_ a "preliminary commitment" is somewhat more restrictive than the division adopted in the [SVG WG charter](https://www.w3.org/Graphics/SVG/svg-2019.html#scope), which suggests that incubation continues until there is an experimental implementation in at least one browser.

**Comment by zed-vector** [comment]
I don't read it as being more restrictive. Work up to the a stage where it is sufficiently developed to attract the involvement of a browser developer IMHO does not preclude further involvement of the CG. Incubation continues until the egg hatches.
