### ISSUE TITLE
[svgcg-2019] Dependencies & Liasons: explicit list or by reference to SVG WG?

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/charter-drafts#201]
Comment on the SVG community group proposed charter, from @frivoal [on the mailing list]:

> Dependencies or Liaisons
> 
> Maybe also list:
> 
> * the CSS-WG (because SVG and CSS overlap at times, and we should coordinate, not duplicate)
> * The horizontal review groups (https://www.w3.org/Guide/process/charter.html#horizontal-review):
>   - WAI Accessible Platform Architectures (APA) Working Group (for accessibility)
>   - Internationalization Working Group
>   - Security Interest Group (for security)
>   - Privacy Interest Group (for privacy)
>   - Technical Architecture Group (for technical architecture principles)

For reference, the current [CG charter “Dependencies and Liaisons” section](https://w3c.github.io/charter-drafts/svgcg-2019.html#liaisons) just defers to the [SVG WG charter](https://www.w3.org/Graphics/SVG/svg-2019.html#coordination):

> Dependencies or Liaisons
> 
> This community group is tightly affilliated with the SVG Working Group. Its work may intersect with the work of any of the other groups mentioned in the “Coordination” section of the SVG working group's charter.

(Note: I need to actually add a link to the SVG WG charter, now that it has a stable URL.)

The referenced part of the SVG WG charter in turn references CSS WG and W3C horizontal review, but is it better to explicitly list those in the CG charter?  Do we expect CG members to directly reach out to these other groups when developing spec proposals, or would that go through the SVG WG?

**Comment by frivoal** [comment]
An incubation focused CG is supposed to socialize it's proposals, so yes, I would expect it to approach WGs directly.
