### ISSUE TITLE
Recommend self-reviews at FPWD and nomination of HR champions

### ISSUE THREAD

**Issue by r12a** [w3c/charter-drafts#213]
It would be useful to add text to the charter to encourage WGs to self-review their specs for horizontal issues (internationalisation, accessibility, privacy, security), and particularly to do so at the time they publish a FPWD. 

It would also be useful to suggest that they nominate a HR champion, who doesn't need to be an expert in HR issues, but would have the responsibility to liaise with the various groups concerned.  We could even have a line for this just below the row at the top of the charter that indicates who the chair and staff contact are.

Having these things in the charter itself will hopefully encourage WGs to pay better attention, since currently it's hard to get the message across, and things are treated as an afterthought, with the consequence that issues still tend to pile up just before CR.

**Comment by samuelweiler** [comment]
I like the suggestion to encourage self-review at FPWD.  I'm less fond of the campion idea.  Let WG chairs manage the delegation (or not) of that work themselves.

**Comment by r12a** [comment]
See also https://github.com/w3c/w3process/issues/130

**Comment by r12a** [comment]
Closing this in favour of https://github.com/w3c/w3process/issues/130
