### ISSUE TITLE
[CSSWG] module splitting / merging and incubation provision

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#217]
"Section 2: Deliverables" of the [previous csswg charter](https://www.w3.org/Style/2016/css-2016) said this:

> This list of modules is not exclusive: The WG may also create new CSS modules, within its scope. Also, it may split or merge CSS modules. If no participant in the group believes a proposed module is out of scope, and the group has consensus to add it, the group may add a new module. If the participants who object sustain their objection after discussion, a re-charter to clarify the scope may be needed.

This is missing in the [proposed 2019 charter](https://w3c.github.io/charter-drafts/css-2019.html). Please restore it.

**Comment by xfq** [comment]
Fixed: https://w3c.github.io/charter-drafts/css-2019.html#deliverables
