### ISSUE TITLE
[csswg] Maintenance of existing CSS RECs should be in scope

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#218]
The last sentence of "Section 2.1: Normative Specifications" of the [previous csswg charter](https://www.w3.org/Style/2016/css-2016) said this:

> Maintenance of existing CSS Recommendations (gathering of errata, publication of new editions incorporating errata) is also in scope.

This is missing in the [proposed 2019 charter](https://w3c.github.io/charter-drafts/css-2019.html). Please restore it.

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/charter-drafts/commit/d938e842ca9ceee7e1a6504c07995c7d66755b70
