### ISSUE TITLE
Definition of interoperable

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-drafts#22]
Re: TTWG charter

> The Working Group is expected to demonstrate at least two ~~interoperable~~ implementations of every available new feature in the recommendations.

_interoperable_ is open to interpretation, e.g. are two presentation processors "interoperable" even if they do not talk to each other? It should be sufficient for the implementations to demonstrate compatibility with the specification.

**Comment by tmichel07** [comment]
changed interoperable to independent
 <li>Include all features that have at least two independent implementations.</li>

Made a PR.

**Comment by palemieux** [comment]
This does not answer the question however. What does "interoperable" mean? The W3C Process document merely speaks of "implementation experience".

**Comment by tmichel07** [comment]
the 2 occurences of the word "interoperable" was simply removed.
Now for the the W3C process, sorry I can't modify it  ;-)

**Comment by nigelmegitt** [comment]
TTWG Meeting 2016-03-10: Agreed to close this issue.
