### ISSUE TITLE
[csswg] mailing list or github or both?

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#220]
In section 6 "Communication ", the [proposed 2019 charter](https://w3c.github.io/charter-drafts/css-2019.html) says this:

>  This group primarily conducts its technical work **pick one, or both, as appropriate**: on the public mailing list public-[email-list]@w3.org (archive) **or** on GitHub issues.

The [previous csswg charter](https://www.w3.org/Style/2016/css-2016) said this:

> This group primarily conducts its technical work via the GitHub issues list, with more general discussion on the public mailing list www-style@w3.org (archive).

I think that was the right answer to the alternative raised, and support keeping the same sentence unchanged.

**Comment by xfq** [comment]
Fixed: https://w3c.github.io/charter-drafts/css-2019.html#communication
