### ISSUE TITLE
[csswg] Decision policy

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#221]
"Section 6: Decision Policy" of the [previous csswg charter](https://www.w3.org/Style/2016/css-2016) said this:

> Decisions are made by consensus of the Working Group. In addition to decisions made on teleconferences or face to face meetings, decisions may also be made by a call for consensus on the public mailing list; consensus to be determined by the chairs after some reasonable interval for objections. 

The [proposed 2019 charter](https://w3c.github.io/charter-drafts/css-2019.html) changes this to:

> To afford asynchronous decisions and organizational deliberation, any resolution (including publication decisions) taken in a face-to-face meeting or teleconference will be considered provisional. A call for consensus (CfC) will be issued for all resolutions (for example, via email and/or web-based survey), with a response period from one week to 10 working days, depending on the chair's evaluation of the group consensus on the issue. If no objections are raised on the mailing list by the end of the response period, the resolution will be considered to have consensus as a resolution of the Working Group. 

I strongly disagree with this change. A mandatory CfC will significantly slow down the work of the Working Group by adding an extra 10 days to any decision. More than just adding 10 days, it will mean than many more topics will remain open in parallel for longer, increasing the mental overhead of editors. While this mode may be accepted in different groups, it would be a radical departure from the way the CSS WG has been operating, with a significant risk to disrupt established collaboration practices. Not only is this mode different from the current way the CSSWG primarily conducts its business, it also significantly restrict the chairs ability to use the write approach for the right situation (mandating a single one for all cases) and their ability to consensually evolve the practices of the working group.

Further, this doesn't buy us anything new:
* The existing decision policy *allowed* chairs to issue calls for consensus anyway, so that they can do so when they feel it is more appropriate.
* The CSSWG's practice, supported by the following paragraph, is that we reopen issues after having resolved them if someone has additional concerns to bring up, so even if we do make hasty and bad decisions once in a while, we will not be stuck with them.

I strongly urge that we revert to the previous wording, which has served us well.

**Comment by xfq** [comment]
I agree with @frivoal here. I reverted it in https://github.com/w3c/charter-drafts/commit/0012af10234d1e695c59908af8853eda44ee68fa

I'll leave the issue open for a while and close it if there's no objection.

**Comment by xfq** [comment]
Closing.
