### ISSUE TITLE
[csswg] Licensing

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#222]
The [previous csswg charter](https://www.w3.org/Style/2016/css-2016) defined that the Group should use the W3C Software and Document license for all its deliverables. [The new one](https://w3c.github.io/charter-drafts/css-2019.html) asks this as an open question, suggesting we might want to use the W3C Document license.

I support continuing to use the W3C Software and Document license over the W3C Document license. In fact, I'd actually be in favor of a more permissive license (such as MIT/X11, or CC BY 4.0)

**Comment by xfq** [comment]
Using the Software and Document license, because that's what we're using for most groups now. Fixed in https://w3c.github.io/charter-drafts/css-2019.html#licensing
