### ISSUE TITLE
[csswg] editorial tweak to avoid ambiguity / contradiction.

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#223]
Both he [previous csswg charter](https://www.w3.org/Style/2016/css-2016) and [the new one](https://w3c.github.io/charter-drafts/css-2019.html) say that:

> There is a single deliverable, the CSS specification. The CSS specification is large, and is divided into a series of modules.

However in success criteria, the old one said (emphasis mine):
> In order to advance to Proposed Recommendation, each **module** is expected to have at least two independent implementations of each of feature defined in the specification.

The new one says:
> In order to advance to Proposed Recommendation, each **specification** is expected to have at least two independent implementations of each of feature defined in the specification.

Given that we have a single specification with multiple modules, we should speak of modules, not specifications, in that sentence.

**Comment by xfq** [comment]
Fixed: https://w3c.github.io/charter-drafts/css-2019.html#success-criteria
