### ISSUE TITLE
[csswg] Change in the testing policy

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#224]
The testing policy described in the [proposed 2019 csswg charter](https://w3c.github.io/charter-drafts/css-2019.html) is significantly different from the one in the [previous csswg charter](https://www.w3.org/Style/2016/css-2016).

I am not necessarily claiming that the old one was perfect, but I see issues with the new one, some of which I consider serious.

Before getting into details, I'd like to say that overall, I acknowledge that the situation with testing in the CSSWG has been suboptimal. However, I believe the problem is primarily caused by insufficient resources being allocated to testing. In that context, I think giving the chairs leeway to adjust and adapt, based on the circumstances, the practices and requirements they place on WG participants in general and Editors in particular is the best thing to do.

I would suggest setting this expectation with something like the following:
> In order to advance to Proposed Recommendation, each module is expected to have at least two independent implementations of each of the features it defines, and to provide evidence for this claim based on tests. The Working Group is therefore expected to proactively work on writing, reviewing, and maintaining tests. Doing so concurrently with its work on specification text is recommended; among other benefits, it helps minimize accidental divergence between implementations and specifications, test results may also inform discussions on specifications, and failing test mail stimulate implementers to update their implementations accordingly. Testing efforts should be conducted via the Web Platform Tests project.

Instead, the proposed rules are:

> There should be testing plans for each specification, starting from the earliest drafts.
>
> [...]
>
> To promote interoperability, all changes made to specifications should have tests:
> * All normative spec changes are generally expected to have a corresponding pull request in web-platform-tests, either in the form of new tests or modifications to existing tests, or must include the rationale for why test updates are not required for the proposed update.
> * Typically, both pull requests (spec updates and tests) will be merged at the same time. If a pull request for the specification is approved but the other needs more work, add the 'needs tests' label or, in web-platform-tests, the 'status:needs-spec-decision' label. Note that a test change that contradicts the specification should not be merged before the corresponding specification change.
> * If testing is not practical due to web-platforms-tests limitations, please explain why and if appropriate file an issue with the 'type:untestable' label to follow up later.

Here are a number of issues I find with this (from the most serious):
* The rule is somewhat ambiguous, which is particularly problematic for a sentence that contains a MUST. It says: "All normative spec changes are generally expected to have [PRs in wpt], or must include the rationale for why test updates are not required". I am not certain that this is intended, but to my reading, the "is expected to do A or must do B" sentence pattern means that B is the only allowed exception to A. Same as "Must do A unless B". In other words, while it looks like an RFC2119 should (due to "generally expected"), it actually behaves as a "must". And that must is problematic:
    * If "required" is to be interpreted as "desirable and technically possible", then it means that in cases where the testing effort is understaffed and stalled, progress on specifications is forbidden. And with MUST semantics, even Chairs cannot override it. Given that understanding of the test effort is a recurrent problem, this may cause the Working Group's pace to grind to a halt.
   * if "required" is intended to mean something else, I don't know what, and cannot understand the rule (or abide by it). If the rule isn't dropped (which I recommend it should be), at least it ought to be clarified, so that we don't postpone finding out what it means to the first time two participants end up in disagreement over it.
    * Another way to look at the sentence is that it is effectively saying "Tests are required unless they are not required". Circular logic is not helpful.
* The first sentence/paragraph is meant as an encouragement to start early, but I worry it could be abused as an excuse by participants in the WG to push back against an otherwise acceptable proposal from another participant with relatively limited resources who can't demonstrate that they have enough resources to "do it all", spec and tests, on their own. Objecting to proposals is of course legitimate, but providing procedural avenues that make it easier to do so in bad faith is a misfeature.
* "Note that a test change that contradicts the specification should not be merged before the corresponding specification change." I agree with this principle, but WPT has its own governance rules, and for instance recently introduced "tentative tests" (see [the definition of `.tentative`](https://web-platform-tests.org/writing-tests/file-names.html)) which are can be merged even when they contradict the spec. WPT governance should be left to WPT.

While I do want to encourage testing, these rules risks making working in the CSSWG prohibitively tedious and slow. Instead of driving up testing, this could drive (some) participants to move to a different venue altogether either for early phases or permanently, where they would neither be bound be the rules of this Charter, nor by those of the W3C Process at large.

Again, I want to reiterate that I think writing tests is important, and that writing tests concurrently with spec work is a good practice, which I apply to own work, and encourage others to follow. However, best practices are not the same as binding requirements.

**Comment by xfq** [comment]
Fixed: https://github.com/w3c/charter-drafts/commit/d2b72c9d50bb7acfb5aac25b6fb1fa56991f3879

Thank you!
