### ISSUE TITLE
[csswg] deliverables should link to current work page

### ISSUE THREAD

**Issue by astearns** [w3c/charter-drafts#225]
The deliverables section has a template link to https://www.w3.org/wiki/[groupname]/PubStatus that needs to be updated. It should probably link to https://www.w3.org/Style/CSS/current-work.en.html

**Comment by xfq** [comment]
Thanks. Fixed in https://github.com/w3c/charter-drafts/commit/2b067e361c83c1d8c93849661aa5fa3690a794bf
