### ISSUE TITLE
[csswg] WICG liaison

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#227]
The liaison section says this:

> The CSS WG may incubate speculative new work in the WICG, and may adopt promising CSS work developed in WICG, provided that RF patent commitments are in place for such work.

Suggest to replace with:
> The CSS WG may adopt promising CSS work incubated in the WICG, provided that RF patent commitments are in place for such work. WICG participants working on CSS-related proposals are expected to coordinate with the CSS WG to ensure timely reviews of their work. Note: No restriction of the CSS WG's ability to adopt proposals developed elsewhere is implied.

* The CSS WG as a whole isn't incubating speculative new work in the WICG, although individuals who participate in the CSSWG might do so.
* Clarifies expectation of coordination wrt reviews; historically CSSWG review has in some cases been requested too late in the process (e.g. lack of fragmentation support in original shipped implementations of ResizeObserver).
* Make it clearer that incubation in WICG isn't required for proposals to come before the CSSWG. (The last minute introduction of this sentence in the previous charter caused strong controversy, as it was perceived as, and used as, an invitation to do incubation in WICG **rather than** within the CSS-WG as has been the traditional work-mode.)
* As stated in the charter template:
    > Do not bury normative text inside the liaison section.

**Comment by plehegar** [comment]
addressed in #232
