### ISSUE TITLE
[csswg] Expected completion dates

### ISSUE THREAD

**Issue by swickr** [w3c/charter-drafts#228]
Could we get more "Expected completion" dates (or perhaps "Estimated") in the 2019 charter?

**Comment by astearns** [comment]
The dates we’ve added are the ones that we think have a chance of completion within the charter period. Anything past that is even more hand wavy guesswork. Do you think there’s a need to add these guesses?

**Comment by swickr** [comment]
Thanks Alan.  A statement to that effect (e.g. "specs the WG hopes to complete within this charter period have expected completion dates indicated") would help set expectations for others who might want to plan their review resources.
