### ISSUE TITLE
Improve the language on horizontal reviews in the template

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#235]
The language about horizontal reviews that was proposed for the CSS WG charter came from the template. After much discussion in https://github.com/w3c/charter-drafts/issues/219, we agreed on a better wording.

This should be applied to the template as well, as the problems discuss in the CSSWG charter, and the solution agreed there, are not specific to CSS.

**Comment by xfq** [comment]
Related: https://github.com/w3c/charter-drafts/pull/240

**Comment by svgeesus** [comment]
Related: https://github.com/w3c/charter-drafts/issues/144

**Comment by svgeesus** [comment]
The language applied to CSS has also been applied to the template, including the addition `s/before entering/before first entering`
