### ISSUE TITLE
Coordination with HTML Accessibility Task Force and the HTML Working Group

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-drafts#24]
Re: TTWG charter

> As needed, the Group will also coordinate with the HTML Accessibility Task Force and the HTML Working Group to contribute how to interoperably implement described video with the Open Web Platform.

Shouldn't this be under Coordination -> W3C Groups

**Comment by tmichel07** [comment]
It was in that section in the current charter
https://www.w3.org/2014/03/timed-text-charter.html
It could be considered as a potential deliverable, but could also fit in the W3C Coordination -> W3C Groups.

**Comment by tmichel07** [comment]
Statement removed.
