### ISSUE TITLE
Duplication of process for W3C process document?

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-drafts#25]
Re: TTWG charter

> Invitation for review must be issued during each major standards-track document transition, including FPWD and CR, and should be issued when major changes occur in a specification.

Doesn't this duplicate process from the W3C Process document?

**Comment by tmichel07** [comment]
I does duplicate with W3C Process.
Will discuss this with PLH.
Either
remove it or wide review for CR.

**Comment by tmichel07** [comment]
chaged MUST into SHOULD.

Invitation for review must be issued

**Comment by palemieux** [comment]
How was this closed?

**Comment by tmichel07** [comment]
Must was replaced with should:

  Invitation for review must be issued during each major standards-track 
document transition, including FPWD and CR, and should be issued when 
major changes occur in a specification.

was changed to

  Invitation for review SHOULD be issued during each major 
standards-track document transition, including FPWD and CR, and should 
be issued when major changes occur in a specification.
