### ISSUE TITLE
[audio-2019] Suggested changes

### ISSUE THREAD

**Issue by chrisn** [w3c/charter-drafts#253]
Doing my AC review of the Audio WG 2019 charter, I have a couple of changes to suggest:

* I'd like to see more detail on the proposed features planned for Web Audio API 2.0, the [v.Next issues list](https://github.com/WebAudio/web-audio-api/milestone/2) linked from the charter shows no open issues

* The Web and TV Interest Group was renamed to Media & Entertainment Interest Group in 2017. The group's scope is not limited to TVs, rather media related features on the web across all devices

**Comment by mdjp** [comment]
V2 issues are in the V2 repo here https://github.com/WebAudio/web-audio-api-v2/projects/1

**Comment by svgeesus** [comment]
Thanks for the report @chrisn now fixed

**Comment by chrisn** [comment]
Thanks @svgeesus :-)
