### ISSUE TITLE
broken links in audio WG charter

### ISSUE THREAD

**Issue by dbaron** [w3c/charter-drafts#254]
While reviewing the [Audio WG charter submitted to the AC](https://www.w3.org/2011/audio/charter/audio-2019-ac.html) which is [maintained in this repository](https://github.com/w3c/charter-drafts/commits/gh-pages/audio-2019.html), I noticed a few broken links:

* in the "Charter History" section, the "Rechartered" that was 22 December 2016 links to the current document rather than to [the previous charter](https://www.w3.org/2011/audio/charter/audio-2016.html).
* The "Yes, it's on GitHub!" text at the very bottom is a 404.

cc @svgeesus

**Comment by svgeesus** [comment]
Thanks for the report @dbaron now fixed
