### ISSUE TITLE
Typo in Testing Policy

### ISSUE THREAD

**Issue by xfq** [w3c/charter-drafts#258]
In https://www.w3.org/2019/02/testing-policy.html :

> If testing is not practical due to web-platforms-tests limitations, please explain why and if appropriate file an issue with the 'type:untestable' label to follow up later.

"web-platforms-tests" should be "web-platform-tests".

**Comment by wseltzer** [comment]
Fixed in the readme from which the text came

**Comment by xfq** [comment]
https://www.w3.org/2019/02/testing-policy.html doesn't seem to be fixed. Some charters quote the text in that page directly, so I suggest that we fix that page as well.

It isn't a substantive change (so we don't need an AC review), so I can fix it if needed.

**Comment by svgeesus** [comment]
testing-policy.html is now fixed

**Comment by xfq** [comment]
Thanks @wseltzer and @svgeesus!

**Comment by Hirammm80** [comment]
> In https://www.w3.org/2019/02/testing-policy.html :
> 
> > If testing is not practical due to web-platforms-tests limitations, please explain why and if appropriate file an issue with the 'type:untestable' label to follow up later.
> 
> "web-platforms-tests" should be "web-platform-tests".
