### ISSUE TITLE
Additional external groups

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-drafts#26]
Re: TTWG charter

Should the following be added to External Groups?
- ARIB (Japan) [ARIB uses TTML in its specifications]
- APEX (in-flight entertainment, http://apex.aero/) [APEX has expressed interest in using TTML in its specifications]

**Comment by nigelmegitt** [comment]
[TTWG Meeting 2016-03-03] Group agreed to add in ARIB but not to add in APEX to the TTWG Charter.

**Comment by tmichel07** [comment]
PR done to add ARIB.
