### ISSUE TITLE
[template] Add a DB link for current charter status

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#260]
I often see that the validity dates in charters get out of date.  Unlike [naming chairs](https://github.com/w3c/charter-drafts/issues/259), I don't think we can remove dates from charters, but can we add a link to the current status, e.g. as shown in https://www.w3.org/Member/Groups

**Comment by svgeesus** [comment]
@samuelweiler do you mean the charter approval dates on that page, or something else?

**Comment by samuelweiler** [comment]
https://www.w3.org/Member/Groups has four things: charter start dates, charter end dates, charter extended end dates, and a single summary date range of overall beginning and end.  The first three have links to the relevant doc and/or announcement.  It provides a way to see if a group is in charter.

The failure mode I have seen is that a charter gets extended but the charter does not get updated, so the group's charter appears to be expired.

**Comment by svgeesus** [comment]
This proposal seems to contradict the existing [policy on charter extension](https://www.w3.org/Guide/process/charter.html#extension) which requires the Team contact updating, in place:

1. the end date
2. the charter history section
3. Any update to the Chair(s), Staff Contact(s), etc.

**Comment by samuelweiler** [comment]
Thanks for flagging that the guide will need to change, also.  Given the responses I've gotten to #259 and #261, I suspect this idea isn't going anywhere, unfortunately.

(And, at this moment, I see fewer mismatches of these dates between the charters and the DB than I saw for chairs and for team contacts.)

**Comment by samuelweiler** [comment]
Looking at this again, months later, I still think it's a good idea.  Specifically, without removing anything, add a link to https://www.w3.org/groups/wg/eowg/charters (for the appropriate group).

**Comment by svgeesus** [comment]
Checking up on the status of this old issue, I see that the charter template now has

> Charter Status 	See the [group status page](https://www.w3.org/groups/wg/[shortname]/charters/) and [detailed change history](https://w3c.github.io/charter-drafts/charter-template.html#history).

where group status page links to the DB-backed charter page for the relevant group.

So it seems this was done at some point and we forgot to close this issue as completed.
