### ISSUE TITLE
Clarification for Success Criteria

### ISSUE THREAD

**Issue by xfq** [w3c/charter-drafts#263]
https://w3c.github.io/charter-drafts/charter-template.html#success-criteria

> In order to advance to Proposed Recommendation, each specification is expected to have at least two independent implementations of each of feature defined in the specification.

It might be useful to mention that it's only needed for *normative* specs, like:

> In order to advance to Proposed Recommendation, each **normative** specification is expected to have at least two independent implementations of each of feature defined in the specification.

Or has it already been implied (because it's impossible to advance a Note-track document to Proposed Recommendation)?

**Comment by svgeesus** [comment]
I think it is already implied, but no harm in the extra clarification
