### ISSUE TITLE
Group intents in switching to Process 2020

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-drafts#264]
When would your Group like to switch to Process 2020?

### ASAP

Service Workers Working Group
Browser Testing and Tools Working Group
Cascading Style Sheets (CSS) Working Group

### At the first opportunity:

Web Performance Working Group
Web Real-Time Communications Working Group
Web Application Security Working Group
Web Applications Working Group
SVG Working Group
Spatial Data on the Web Working Group (to be created from IG)

### Sure...

WebAssembly Working Group
Timed Text Working Group
Pointer Events Working Group
Web Fonts Working Group
Internationalization Working Group
Accessible Rich Internet Applications Working Group
Accessible Platform Architectures Working Group
Accessibility Guidelines Working Group

### When charters expires:

JSON-LD Working Group
Audio Working Group
Automotive Working Group
Dataset Exchange Working Group
Decentralized Identifier Working Group
Devices and Sensors Working Group
Distributed Tracing Working Group
HTML Working Group
Immersive Web Working Group
Media Working Group
Publishing Working Group
Second Screen Working Group
Verifiable Credentials Working Group
Web Authentication Working Group
Web of Things Working Group
Web Payments Working Group
Web Platform Working Group
Accessibility Guidelines Working Group
MiniApps Working Group (TBD)
Web GPU Working Group (TBC)
Web Transport Working Group (TBC)
EPUB3 Working Group (TBC)

### Not impacted anyway

Accessibility Education and Outreach Working Group

**Comment by samuelweiler** [comment]
What is the "issue" here?

**Comment by plehegar** [comment]
this is simply documenting the current intent of the Working Group and providing a place to discuss it.

**Comment by fantasai** [comment]
I don't see a reason why we shouldn't be adopting P2020 across all WGs, just as we adopted P2019. P2020 is backwards-compatible with P2019. But the Patent Policy does need to be an explicit switch.

**Comment by plehegar** [comment]
Plan is to adopt P2020 for all Groups as it becomes effective. For PP2020, it will be gradual.

**Comment by plehegar** [comment]
[close to avoid future confusion while we're surveying the Groups]
