### ISSUE TITLE
Charters should be explicit about a group intents to publish Recommendations or simply publishing CR Snapshots

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-drafts#275]
Though Process 2020 allows a Working Group to publish as they wish as long as the document is on the REC-track (modulo update/transition requests), a Group may choose not to publish a Recommendation (see also https://github.com/w3c/w3process/issues/443). It would be good to indicate the Group intend in the charter if known.

**Comment by swickr** [comment]
You're referring to a Group that intends that the end state is a series of CR Snapshots.  As in #274, I agree this should also be explicit in the charter.

**Comment by svgeesus** [comment]
So https://www.w3.org/2020/Process-20200915/#transition-pr is about stronger emphasis on getting to Rec, to ensure HR happens and issues are addressed; it also touches on what it means for a spec to be "maintained".

Putting optional boilerplate in a charter that says "we expect to hang around in CR forever" seems to encourage an anti-pattern therefore; unless the wording focuses more on "how will you demonstrate the CR is maintained and not abandoned".

**Comment by svgeesus** [comment]
Discussed on 8 Dec 2020 strat call; unless the AC is requesting this, it seems premature to add this to the charter. The inclination was to close this with no change.

**Comment by plehegar** [comment]
So, we don't make the participants intent in the charter if they have one? I understand the worry about encouraging folks not to get to REC but saying nothing in the charter if the intent is known doesn't help imho.

**Comment by samuelweiler** [comment]
I think https://github.com/w3c/charter-drafts/pull/343 resolves most of this, but perhaps we should also take out the "expected completion" line in the deliverables list?

**Comment by wseltzer** [comment]
WebAppSec used: the Working Group intends to publish the latest state of their	work as Candidate Recommendation (with Snapshots). The group will advance documents to Recommendation when they are sufficiently mature, with no explicit milestones.
https://github.com/w3c/webappsec/pull/581

**Comment by svgeesus** [comment]
Add the WebAppSec wording (if approved following AC review) to the template as one option.

**Comment by plehegar** [comment]
cc @dontcallmedom

**Comment by dontcallmedom** [comment]
I am unconvinced the text about CR Snapshots and Rec when mature adds anything - this is exactly what any WG is expected to do.

**Comment by nigelmegitt** [comment]
> I am unconvinced the text about CR Snapshots and Rec when mature adds anything - this is exactly what any WG is expected to do.

If the suggestion is that some WGs expect _not_ to advance to Rec when sufficiently mature, then I would agree that a) that should be discouraged and b) it should be explicitly stated. But I'd much prefer that WGs _are_ expected to advance to Rec when adequately mature.

**Comment by plehegar** [comment]
At this point, we've been sending charters to the AC with the intent of the Working Group. Is there anything else that needs to be fixed?

**Comment by plehegar** [comment]
closing this for now. feel free to re-open if you believe this is still an issue.
