### ISSUE TITLE
[decentralized] Where do you want to discuss this draft charter?

### ISSUE THREAD

**Issue by wseltzer** [w3c/charter-drafts#278]
Thanks @jwrosewell for the discussion draft of a Decentralized Web Interest Group charter. I've merged the draft and made a PR #277  to add "DRAFT" to its labeling. 

Where would you recommend that we invite people to discuss the charter itself? In github issues in this or a different repository? (The links in the box at the top are incomplete.)

**Comment by jwrosewell** [comment]
Thank you. Could we use github issues in this repository for discussion on the charter?

**Comment by wseltzer** [comment]
Sure.  You might suggest people tag their subject line as I did here, e.g. 
https://github.com/w3c/charter-drafts/issues/new?title=[decentralized]

**Comment by wseltzer** [comment]
Merged https://github.com/w3c/charter-drafts/pull/279
