### ISSUE TITLE
[svg] GH does not reflect current team contact; no history entry for team contact change

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#294]
It appears that the SVG charter was updated in CVS to show a new team contact, but that change (and others?) was not backported to this Github repo, even though the charter points to this repo (including for issues like this one).  Additionally, the history table in the charter was not updated to reflect the team contact change (and perhaps others?).

**Comment by svgeesus** [comment]
This seems to be a fundamental misunderstanding on the purpose of this repo. From the README:

> This repo is a space for _draft_ charters _to be developed_ for W3C Working Groups or W3C Interest Groups, to be discussed and refined. No charters that get added to this repo necessarily have _any official standing at all_

@samuelweiler you seem to be under the impression that this is also the official repository of all non-draft charters. If you want that to be the case you should propose it and get consensus on this expansion of scope.

**Comment by plehegar** [comment]
The approved charters are in w3.org, not GH, since they are subject to strict rules for changing them.

**Comment by samuelweiler** [comment]
> This seems to be a fundamental misunderstanding on the purpose of this repo. From the README:
> 
> > This repo is a space for _draft_ charters _to be developed_ for W3C Working Groups or W3C Interest Groups, to be discussed and refined. No charters that get added to this repo necessarily have _any official standing at all_
> 
> @samuelweiler you seem to be under the impression that this is also the official repository of all non-draft charters. If you want that to be the case you should propose it and get consensus on this expansion of scope.

No; I don't need this repo to be the repo for non-draft charters.  I only filed this because I saw that the charter specifically pointed at this repo: "This charter is available on GitHub. Feel free to raise issues."  Perhaps that's not what you intended with that pointer?

In any case, I think the history table (in the published charter) should still be updated to show the team contact change, even if PLH chooses to not backport that change into this repo.

**Comment by svgeesus** [comment]
> I think the history table (in the published charter) should still be updated to show the team contact change

Agreed
