### ISSUE TITLE
[template] HR review "3 months" text re: process 2020?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#298]
The current template says:

"Group is advised to seek a review at least 3 months before first entering CR ..."

How should that change based on Process 2020?

**Comment by svgeesus** [comment]
I don't see anything in Process 2020 [6.1.2.1. Wide Review](https://www.w3.org/2020/Process-20200915/#wide-review) that would necessitate a change to reviews before entering CR. Did you have something specific in mind?

Or were you thinking of the review of [Candidate Additions](https://www.w3.org/2020/Process-20200915/#candidate-addition), which does not involve a CR step at all?

> In addition to their actual maturity level, published REC Track documents with candidate changes are also considered, for the purpose of the W3C Patent Policy [PATENT-POLICY], to be Working Drafts with those candidate changes treated as normative.

**Comment by plehegar** [comment]
[closing since latest Processes did not do any change in this area. feel free to re-open if you feel otherwise]
