### ISSUE TITLE
[template] remove performance from HR review?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#301]
Why is performance listed in the required HR reviews?

"For all specifications, this (Working|Interest) Group will seek horizontal review for accessibility, internationalization, performance, privacy, and security"

**Comment by svgeesus** [comment]
Why do you want to remove it?

Performance is clearly something that can apply to all specifications. It is thus clearly horizontal.

Also, it is a good example of a tradeoff. For example, some feature or some mitigation might improve one aspect at the expense of severely degraded performance, and ths needs to be taken into account.

I oppose the removal of performance.

**Comment by samuelweiler** [comment]
> Why do you want to remove it?

Because, unlike the others, we're not directing groups re: where to get that review.

(Alternatively: where should groups ask for that review?  I thought this was about naming things that they need to specifically seek (and that we tell them how to seek)...)

**Comment by wseltzer** [comment]
Perhaps "will consider performance," since we don't have a specific place to direct them for review

**Comment by samuelweiler** [comment]
from strat 2 March 2021, change this to "consider" rather than HR.  https://www.w3.org/2021/03/02-strat-irc#T14-24-32
as success criteria
