### ISSUE TITLE
[template] time to add the TAG design principles

### ISSUE THREAD

**Issue by svgeesus** [w3c/charter-drafts#303]
The document is still being worked on, but I wonder if it is time to add something like

> we expect to follow the [TAG Design Principles](https://w3ctag.github.io/design-principles/)

**Comment by wseltzer** [comment]
Sounds premature. When does TAG plan to share these design principles more widely/formally?

**Comment by svgeesus** [comment]
I hear from a TAG member that the Process Document does not allow the TAG to publish on /TR !!

https://github.com/w3c/w3process/issues/429
https://github.com/w3c/w3process/issues/461

Which makes it hard to share more formally. TAG reviews regularly use these design principles though.

**Comment by svgeesus** [comment]
Given response from TAG, and also confirmation that WHATWG already follows them, I plan to add this to the template.

**Comment by wseltzer** [comment]
Let's discuss

**Comment by svgeesus** [comment]
> I hear from a TAG member that the Process Document does not allow the TAG to publish on /TR !!

This was fixed in Process 2021

> When does TAG plan to share these design principles more widely/formally?

If the question is "when will they be done" then the answer is that they are taking a living standard approach and the principles are continuously evolving. If the question is "when is it appropriate to cite them" then Horizontal Review already includes TAG review, which includes checking the box that the Design Principles have been read. 

If work is going to fail TAG review due to breaking the TAG design principles then it seems that charters should by default include wording that the WG intends to follow them.

**Comment by svgeesus** [comment]
Since this has been Agenda+ for 18 months without actually being discussed, I raised an issue on the TAG design principles repo:

 - https://github.com/w3ctag/design-principles/issues/407

**Comment by svgeesus** [comment]
Closed since the TAG agreed that charters should include an expectation to follow these, so I added it to the template.
