### ISSUE TITLE
[service workers] remove "other charter" link

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#307]
Section 2.1 has a link to the current/old charter, which seems odd.

**Comment by plehegar** [comment]
This link is required by the Process.
[[
The stable URL of the Working Group charter under which the Exclusion Draft was published (labeled the “Other Charter”).
]]
https://www.w3.org/2020/Process-20200915/#WGCharter

**Comment by samuelweiler** [comment]
Weird.  OK.
