### ISSUE TITLE
[service workers] Scope and deliverables

### ISSUE THREAD

**Issue by wseltzer** [w3c/charter-drafts#325]
From the draft charter's references to other deliverables, it's implied (but not clearly stated) that yet other deliverables would be out of scope without a re-chartering. If that's the intent, say so directly, with: 

>   If additional in-<a href="#scope">scope</a> Recommendation-track deliverables need to be added to the Charter before the Charter expires, the Working Group will prepare an updated Charter that differs only in deliverables.

See also https://github.com/w3c/charter-drafts/pull/324

**Comment by ylafon** [comment]
That was indeed the intent (based on the FO during the last charter review)
