### ISSUE TITLE
Update list of OGC WGs involved in liaison

### ISSUE THREAD

**Issue by chris-little** [w3c/charter-drafts#327]
Section 4.2
`Web Coverage Services (WCS) SWG, Features API SWG, Web Mapping Service (WMS) SWG, OGC API - Records SWG
    These Working Groups develop technologies including OGC API: Features and OGC API: Records that will likely be discussed within the Spatial Data on the Web Working Group.`

should reflect the recent names changes:
`OGC API-Coverages SWG, API-Maps SWG, API-Features SWG, API-Records SWG, API-EDR SWG
    These Working Groups develop technologies including OGC API-Features and OGC API-Records that will likely be discussed within the Spatial Data on the Web Working Group.`

Perhaps could mention the (legacy?) WFS, WCS, WMS services?

**Comment by samuelweiler** [comment]
I assume this is about the spatial data on the web IG.  Where is that draft charter?

**Comment by chris-little** [comment]
@samuelweiler This was a misplaced and missed comment on the [Charter](https://w3c.github.io/sdw/roadmap/charter-2020.html) which is now accepted.
