### ISSUE TITLE
[browser testing and tools] test report list of browsers

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#330]
The language around the list of engines for which test reports will (or may?) be generated is a little unclear.  Do you mean _these_ engines (as a mandatory list) or is this a list of examples?  If the former, say "these", if the latter, just remove them.

And do you really want edge in there separately?

**Comment by samuelweiler** [comment]
Recent edits seem to have addressed this.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/w3c/charter-drafts/issues/330#issuecomment-776300655
