### ISSUE TITLE
[browser testing and tools] markup validation issues

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/charter-drafts#350]
_This comment is for the [new Browser Testing and Tools Working Group Charter](https://w3c.github.io/charter-drafts/browser-testing-tools.html)._

In this new charter I noticed a couple of markup issues reported by validator Nu see:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fcharter-drafts%2Fbrowser-testing-tools.html

Please also use `https://` for the link to the public-browser-tools-testing mailing list archives:
`https://lists.w3.org/Archives/Public/public-browser-tools-testing/`
(this would avoid an unneeded redirect)

**Comment by sideshowbarker** [comment]
> In this new charter I noticed a couple of markup issues reported by validator Nu see:
> [validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fcharter-drafts%2Fbrowser-testing-tools.html](https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fcharter-drafts%2Fbrowser-testing-tools.html)

Fixed now — https://validator.w3.org/nu/?doc=https://w3c.github.io/charter-drafts/browser-testing-tools.html

> Please also use `https://` for the link to the public-browser-tools-testing mailing list archives:
> `https://lists.w3.org/Archives/Public/public-browser-tools-testing/`
> (this would avoid an unneeded redirect)

Yep — thanks for catching that; fixed now
