### ISSUE TITLE
Date of SVG charter validity?

### ISSUE THREAD

**Issue by ghost** [w3c/charter-drafts#352]
Hi,

According to https://www.w3.org/Graphics/SVG/svg-2019.html the charter "ran out" at the end of March.

![Charter dates](https://user-images.githubusercontent.com/12199980/115928879-226c5f80-a487-11eb-856b-43de956b44f5.png)

Is a replacement coming or will the dates just be prolonged?

Thanks,
Sanja

**Comment by plehegar** [comment]
we're working on a new charter that will only be there for maintenance purpose. We don't expect a lot of activity from this Working Group, if any, however. The interest to do more work on the specification is too low at the moment.

**Comment by ghost** [comment]
Thanks for the reply, @plehegar.
