### ISSUE TITLE
[template] Scope should be scope (only)

### ISSUE THREAD

**Issue by svgeesus** [w3c/charter-drafts#355]
The charter template does not have an **Introduction** or **Background** section, although some charters have added this.

The charter template leads off with a **Scope** section. AC Reps tell us that they want the Scope section to be brief, and solely dedicated to stating what exactly is _in scope_ or _out of scope_.

The charter template contradicts this and encourages using the Scope section to describe the background, as follows:

```html
<p><i class="todo">Brief background of landscape, technology, 
  and relationship to the Web, users, developers, implementers, and industry.</i></p>
```

This should be fixed by 

1. Adding a **Background** section
2. Moving the quoted instructions on "brief background" to the Background section
3. Adding brief instructions to the **Scope** section

**Comment by svgeesus** [comment]
@wseltzer this addresses the comment you made (originally in relation to the PNG G charter) can you confirm your concerns are addressed by the related PR?

**Comment by wseltzer** [comment]
thanks @svgeesus, LGTM
