### ISSUE TITLE
[svg-2021] Wrong description of SVG Native

### ISSUE THREAD

**Issue by svgeesus** [w3c/charter-drafts#360]
The description of SVG Native is for an entirely different specification!

> This specification defines the mapping between (non-ARIA) SVG features and OS platform accessibility application programming interfaces. 

use the abstract instead in the charter:

> SVG Native is a profile of SVG designed for interoperability with native apps and system libraries that execute outside the Web environment, and thus cannot rely on features such as linking, interactivity, animation, or the Web security model.

(I changed "SVG 1.1" to "SVG" to leave open whether the profile is of 2.0 or 1.1)

**Comment by svgeesus** [comment]
@marcoscaceres ?

**Comment by marcoscaceres** [comment]
Oops, indeed copy/pasta from the old charter. Thanks for letting me know!
