### ISSUE TITLE
[template] Link to charter status page

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#378]
Let's add a link to the header of all charters pointing at the group's charter status/history page, e.g. https://www.w3.org/groups/wg/browser-tools-testing/charters.  That could eliminate the need to update old charters to point to new ones.  @koalie 

Thanks to @tantek for the inspiration: https://w3ccommunity.slack.com/archives/C010204K9AN/p1623902700001000

**Comment by koalie** [comment]
YES!
![make it so](https://user-images.githubusercontent.com/3716853/138294728-fe23f4d1-61fe-4e48-a4f4-e79b26a78591.gif)
... please

**Comment by plehegar** [comment]
+1. @samuelweiler , will you do a pull request or do you have a suggestion on who should do it?
