### ISSUE TITLE
[template] Consistent markup between the charter template and the deliverables tool

### ISSUE THREAD

**Issue by svgeesus** [w3c/charter-drafts#385]
The [charter template](https://w3c.github.io/charter-drafts/charter-template.html) uses a definition list, with one `dt` per normative specification:

```html
<dt id="web-foo" class="spec"><a href="#">Web <i class="todo">[spec name]</i></a></dt>
            <dd>
              <p>This specification defines <i class="todo">[concrete description]</i>.</p>

              <p class="draft-status"><b>Draft state:</b> <i class="todo">[No draft | <a href="#">Use Cases and Requirements</a> | <a href="#">Editor's Draft</a> | <a href="#">Member Submission</a> | <a href="#">Adopted from WG/CG Foo</a> | <a href="#">Working Draft</a>]</i></p>
              <p class="milestone"><b>Expected completion:</b> <i class="todo">[Q1–4 yyyy]</i></p>
```

The (Team-only) deliverables tool, for example https://www.w3.org/groups/wg/audio/deliverables  uses a `li` per normative specification. All the info is there but it requires tedious copy and paste to put the info from the tool into the form expected by the template

```html
<li id='3147' class='spec'>
                            <a href='https://www.w3.org/TR/audioproc/' rel='versionof'>Audio Processing API</a></li>
                        <ul>
                            <li>Latest publication: <a href='https://www.w3.org/TR/2011/WD-audioproc-20111215/'>2011-12-15</a></li>
                            <li>Exclusion Draft:
                                <a href='https://www.w3.org/TR/2011/WD-audioproc-20111215/'>https://www.w3.org/TR/2011/WD-audioproc-20111215/</a></li>
                            <li>associated <a href='https://lists.w3.org/Archives/Member/member-cfe/2011Dec/0019.html'> Call for Exclusion</a>
                                on 2011-12-15
                                                                    ended on 2012-05-13
                                                            </li>
```

It would be much more convenient and less error prone if the tool generated the exact markup required for the charter section.

**Comment by svgeesus** [comment]
It isn't clear who wrote the tool, or where the source is. Should I contact sysreq to ask about it?

I have also in the past tried pasting the output of the tool into a charter, but there was (reasonable) pushback since the deliverables list was not using the markup in the charter template.

Updating the tool to generate the correct markup seems the way forward, therefore.

**Comment by plehegar** [comment]
cc @vivienlacourba . is there anyone who can help here?

**Comment by vivienlacourba** [comment]
> cc @vivienlacourba . is there anyone who can help here?

Yes that's certainly something @deniak can look at (note that it might take a few weeks as I'm keeping Denis quite busy those days).

**Comment by deniak** [comment]
We have updated the deliverables page to match the markup from the charter template. We have also included some additional information such as the 'draft state' and the spec description.
