### ISSUE TITLE
[Web Assembly] source alternative / auditability

### ISSUE THREAD

**Issue by samuelweiler** [w3c/charter-drafts#391]
More substantively on the security side, what provisions are available for auditing WebAssembly code? Are there things we can do to make it more auditable?

I'm imagining, for instance, a requirement that the WebAssembly always be optional - making a compilable/readable version available that a browser can always load as an alternative.  And perhaps output be deterministically compilable from source.

[also raised in https://github.com/w3c/strategy/issues/325#issuecomment-1104348092, but the Pipeline card doesn't say where you want issues raised...]

**Comment by plehegar** [comment]
@ericprud , can you look into this?

**Comment by ericprud** [comment]
trying to get back from bike trip (train issues). will look Mon or Tue

**Comment by ericprud** [comment]
I believe this cab be closed based on [w3c/strategy#325](https://github.com/w3c/strategy/issues/325#issuecomment-1129803779).
