### ISSUE TITLE
[wot-cg] Specifying the chair election process

### ISSUE THREAD

**Issue by egekorkan** [w3c/charter-drafts#393]
After the draft of #392, the part regarding the chair election needs to be more precise but at the same time deadlock-free. The aim is to have a specific way to elect chairs. This means:
- Removing the first part that says `Participants in this group choose their Chair(s) and can replace their Chair(s) at any time using whatever means they prefer`.
- Structuring the remaining part so that if there are less than 5 people in the CG or if all the CG participants are from the same organization, there is still a way to select chair(s), thus no deadlocks. This can be done by adding a paragraph that explains an exception handling algorithm (like majority vote etc.)

**Comment by egekorkan** [comment]
- [x] The chairs' current idea is to say that if there is a deadlock or corner case, Community Development Lead MUST be consulted.

**Comment by plehegar** [comment]
This seems to have been resolved. Re-open if that's not the case.
