### ISSUE TITLE
[wot-cg] Specifying the contribution mechanics

### ISSUE THREAD

**Issue by egekorkan** [w3c/charter-drafts#394]
At #392 , the contribution mechanics does not mention how and where the emailing list is used versus GitHub functionalities. We should be specific and informative on how people should use one or the other. 
Also, we should explain that organizing events (hackathons etc.) can be governed by other documents (reports?) that the CG publishes

**Comment by egekorkan** [comment]
Regarding emailing vs GitHub: 

- [x]  Emails can be used for announcements but everything else that benefits from a discussion, MUST happen via GitHub (issues, discussions, projects). 

Regarding chat platforms:
- [x]  Any discussion that does not happen in GitHub, is not considered official.

Feedback and Question Mechanism:
- [x] There will be people reading the WoT specifications and having questions. We should encourage them to post it in the community group. This can be via disclaimer/note as an issue template in WoT WG/IG repositories.

**Comment by plehegar** [comment]
This seems to have been resolved. Re-open if that's not the case.
