### ISSUE TITLE
[CG template] Decision Process links to itself

### ISSUE THREAD

**Issue by egekorkan** [w3c/charter-drafts#396]
The decision process section links back to itself via https://w3c.github.io/cg-charter/CGCharter.html#decision . Is this intended to be like this or should each CG change it to another link?

**Comment by svgeesus** [comment]
Looks like that self-link was in [the first draft](https://github.com/w3c/cg-charter/commit/2b580d0ec3936f70215fb04289c7aba712da1de0) and no-one noticed.

Reading the section, it seems that the expectation is that each CG will decide and then document their decision process, so the link should probably go to where an individual CG stores that. I don't know if any existing CG do this, however.
