### ISSUE TITLE
[wg/json-ld] RDF-DEV CG listed twice

### ISSUE THREAD

**Issue by gkellogg** [w3c/charter-drafts#401]
The coordinated groups includes RDF-DEV CG twice.

Arguably, saying that **RDF Dataset Normalization** is out of scope doesn't make much sense, given the existence of the RDF-RCH working group.

**Comment by gkellogg** [comment]
@plehegar this wasn't addressed in the updated charter document.

Work on integrating support for RDF-star I expect to be covered by the normal maintenance provision, under coordination with the RDF-star WG. Normalization is obviously covered by the RCH WG, and has no bearing on JSON-LD.

cc/ @BigBlueHat

**Comment by plehegar** [comment]
I don't see [RDF-DEV CG listed twice](https://www.w3.org/2023/01/json-ld-wg-charter.html#coordination) so assuming this got resolved somehow.

Feel free to re-open if there is still an issue.
