### ISSUE TITLE
[wg/webtransport] Comment from Mozilla

### ISSUE THREAD

**Issue by ylafon** [w3c/charter-drafts#409]
This is about a proposed change in the PR entrance criteria.
See https://lists.w3.org/Archives/Public/public-new-work/2022Oct/0000.html
Discussion happening in the WG: https://github.com/w3c/webtransport/issues/444

**Comment by plehegar** [comment]
The charter was approved.
https://lists.w3.org/Archives/Member/w3c-ac-members/2023JanMar/0014.html
