### ISSUE TITLE
[template] Stylesheet blocked due to mixed active content

### ISSUE THREAD

**Issue by csarven** [w3c/charter-drafts#413]
I'm not sure where to raise this issue for consideration besides here. Please transfer as you see fit. Tagging @plehegar since you were mentioned in the pubrules-style.css as author/committer.

---

charter-template.html links to stylesheet at https://www.w3.org/OldGuide/pubrules-style.css which then imports http://www.w3.org/StyleSheets/base.css .

Note the `https` and `http` in the first and second stylesheet URLs respectively.

Browsers block fetching the `http` due to "mixed active content".

Suggestion: change `http` to `https`.

**Comment by svgeesus** [comment]
I see that the import has been edited to use https meanwhile. Closing this as done, therefore.
