### ISSUE TITLE
[template] Remove reference to Director

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-drafts#422]
[[
All decisions made by the group should be considered resolved unless and until new information becomes available or unless reopened at the discretion of the Chairs or the Director.
]]

should read
[[
All decisions made by the group should be considered resolved unless and until new information becomes available or unless reopened at the discretion of the Chairs.
]]

**Comment by plehegar** [comment]
@frivoal , do you see any issue with applying the change?

**Comment by frivoal** [comment]
Nope, seems perfectly fine. thanks for finding this.
