### ISSUE TITLE
[wg/did] Allow work on DID Core v2.0 and allow it to advance to Candidate Recommendation

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-drafts#429]
From @msporny:
[[
Allow work on DID Core v2.0 and allow it to advance to Candidate Recommendation (allowing class 4 changes based off of lessons learned around media types and transformations made during the VCWG v2.0 work).
]]
From [2023 AC review](https://lists.w3.org/Archives/Public/public-new-work/2023Aug/0003.html).

**Comment by msporny** [comment]
Digital Bazaar is undecided on whether or not this is a good idea. 

It would probably be good for the ecosystem to have a significant update to specific parts of the specification, but the WG could be taking on A LOT of work unless we were to tightly constrain v2.0 to a very specific list of improvements.

**Comment by pchampin** [comment]
From @OR13
[[
Allow work on DID Core v2.0 and allow it to advance to Candidate
Recommendation (allowing class 4 changes based off of lessons learned
around media types and transformations made during the VCWG v2.0 work).

The previous version of the specification suffered from a charter that made addressing media types very difficult, and resulted in inelegance when relating the two core concepts related to decentralization objectives, namely “decentralized urls” (identifiers for identities) and “decentralized media types” (representations of identity documents).

This created an “abstract data model” that was only comprehensible through the lens of JSON-LD and RDF.

We feel it will be necessary to make breaking changes to correct the standard.
]]
From [2023 AC Review](https://lists.w3.org/Archives/Public/public-new-work/2023Aug/0015.html).

**Comment by pchampin** [comment]
[[
Finally, we object to restrictions on significant breaking changes in DID Core v2.0. The lack of media type coherence in the first version requires fully breaking changes to correct and enhance usability and as is the data model is effectively unusable across did methods which defeats the purpose of standardizing a data model in the first place.
]]
From [2023 AC Review](https://www.w3.org/2002/09/wbs/33280/did-wg-2023/results) (member-only).

**Comment by rxgrant** [comment]
This does not have support from Digital Contract Design at our current level of understanding.  However, we would be happy to engage in ...WG meetings to understand it better.

One path that may help unbind RDF complications from the Data Model might be to specify a simplified subset of JSON-LD that does not rely on all the graph traversal stuff.  I'm not even sure if this is what the concern is here, but if it is, support may be gathering for that.

**Comment by plehegar** [comment]
The charter was [announced ](https://lists.w3.org/Archives/Public/public-did-wg/2024Apr/0000.html)
