### ISSUE TITLE
Define a goal to define use of TTML with HTML5 text track model

### ISSUE THREAD

**Issue by andreastai** [w3c/charter-drafts#43]
Part of the mission in the TTWG charter should be to improve interoperability between the HTML5 spec and the TTML specs. This should be done by defining how TTML can be used as "caption" or "subtitles" format for HTML5 text tracks. This requires the colloboration with other group (e.g. the Web Platform Working Group).

**Comment by nigelmegitt** [comment]
Can't this be closed now since #44 has been merged?
