### ISSUE TITLE
[wg/did] Make it explicit that WG agreement is to begin the process of developing DiD Methods

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-drafts#434]
[[
propose to clarify in the Charter that no DID method will begin the process of being developed if the WG can't agree on which DID methods.
]]
From [2023 AC review](https://www.w3.org/2002/09/wbs/33280/did-wg-2023/results).

**Comment by rxgrant** [comment]
Strong objection to resolving this outside the chartering process.  To delay the issue is to ignore the formal objections.  If decisions are to move forward, look for consensus.  

One easy avenue for consensus is to not leave open the door for standardizing DID Methods when there is not consensus to do so.

Instead, charter a WG that would have consensus to work on a specific DID Method.

**Comment by rxgrant** [comment]
Also, this was publicly formally objected to.  Not sure why we have to restate what has been clearly stated.  What is the process here?

**Comment by rxgrant** [comment]
@iherman I have a process question [here](https://github.com/w3c/charter-drafts/issues/434#issuecomment-1715535627).  What is the process requirement to restate what has already been formally objected to?

**Comment by iherman** [comment]
@rxgrant,

I am not sure that I fully understand what you want to achieve. But I was not part of the chartering process, I was only asked occasionally to comment on specific questions; @pchampin has more insight. 

However, slightly in the abstract, here are my reactions, FWIW.

- _If the goal is to simply **disallow** the definition of any new DID methods:_  This can (and, under the circumstances, probably should) be stated in the "§2.1 Out of Scope" section.
- _If the goal is to allow the definition of a new DID methods, albeit not as Recommendations:_ We fall back on the discussion elsewhere: such a Method would be published as a Note and, as I said several times, the creation of a completely new Note would require a formal W3C Resolution (see my comment at https://github.com/w3c/charter-drafts/pull/448#discussion_r1378708311). Ie, the consensus requirement is covered by the process. However, if very necessary, this could be made explicit in the "§3.2 Other Deliverables" and/or "§2 Scope" sections saying something like 
    
    > New DID Methods may be published as Working Group Notes, subject to a consensus of the Working Group.

    Such a statement would be, from the point of view of the process, slightly redundant, but can be put into the charter IMHO.
- _If the goal is to **standardize** one or several Methods:_ in my view, this is not possible under this charter (I refer to the [version written up by @pchampin](https://htmlpreview.github.io/?https://raw.githubusercontent.com/w3c/charter-drafts/did-wg-2023-team-proposal/2023/did-wg.html)). New Recommendation deliverables, that are not listed in the charter as such (i.e., as part of the "§3.1 Normative Deliverables" section) would require either a separate WG with a new charter, or a rechartering of the current WG.


Note that this current issue has been raised by @plehegar, whose knowledge of the process is many times more accurate than mine, so his reactions might be much more relevant.

**Comment by plehegar** [comment]
The charter was [announced ](https://lists.w3.org/Archives/Public/public-did-wg/2024Apr/0000.html)
