### ISSUE TITLE
[template] Removal of the words "all known" in the current charter template

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-drafts#435]
[[
I have a concern (objection) about the removal of the words "all known" in the current charter template, made in #415 .

The original phrasing, which I would prefer to continue use, was:

> Each specification should contain sections detailing all known security and privacy implications for implementers, Web authors, and end users.

As I describe in the [PATCG charter issue](https://github.com/patcg/patwg-charter/pull/60) where this change was proposed, I believe that this is a step in the wrong direction, I don't believe the concern of disruption to WGs through "weaponisation" of that requirement to be well founded, and we shouldn't be loosening the requirements on WGs to document privacy considerations, even with strong horizontal review in place, as we have.
]]
From @chrisn https://github.com/w3c/charter-drafts/issues/416#issuecomment-1680512396

**Comment by samuelweiler** [comment]
For the historical context, see: https://github.com/w3c/charter-drafts/pull/415

My summary: #415 was merged without consensus.  I'm not sure whether it's better to revert #415 while we sort out a consensus or not.

**Comment by chrisn** [comment]
I would prefer us to do that, as I'm seeing charters coming through for AC review with that change included, and I don't want to be objecting to everything.

**Comment by samuelweiler** [comment]
Per strategy team discussion 19 September 2023, rolling back the change in 415.
