### ISSUE TITLE
[template] Rethink the "intents to implement" wording

### ISSUE THREAD

**Issue by jyasskin** [w3c/charter-drafts#436]
The charter template includes "<em>Consider adding this clause if the Group does not intend to move to REC:</em> All new features should be supported by at least two intents to implement before being incorporated in the specification."

I see 2 problems here:

1. As @hober recently pointed out, not all browsers use intents at all. Even Chromium doesn't use the "Intent to Implement" anymore: it's now an "Intent to Prototype". I think the goal is relatively clear--this wants two implementers to state that they plan to implement the feature before it lands in a specification--but the wording isn't ideal.

2. I'm not sure this is actually the bar we want for living standards. The template's wording roughly matches the WHATWG's [working mode](https://whatwg.org/working-mode#additions), in requiring 2 implementers to say "we would like to implement this soon", but it's less than the W3C's current bar for [transitioning to PR](https://www.w3.org/2023/Process-20230612/#transition-pr) that there's adequate implementation experience. When a group doesn't intend to ever transition to PR because it doesn't want to freeze the specification for AC review, its charter should still say how the group will mark the features that have independent interoperable implementations. https://github.com/patcg/patwg-charter/pull/62 suggests one way to do this, but it's not the only possibility.

**Comment by npdoty** [comment]
Agreed / see also: https://github.com/w3c/charter-drafts/issues/432

**Comment by hober** [comment]
Apparently @plehegar disagrees with my concern here, but I don't understand the nature of his disagreement.

**Comment by plehegar** [comment]
@hober , seeing your proposed change makes me realize we did not have a disagreement.

**Comment by svgeesus** [comment]
I agree the current wording does not express what we are trying to say here
