### ISSUE TITLE
[wg/did] Document how current implementers interop using DID-core-v1

### ISSUE THREAD

**Issue by rxgrant** [w3c/charter-drafts#438]
A good recommendation heard in the DID-WG charter discussion:

  - Maintenance charter for DID-core should explicitly document how current implementers interop using DID-core-v1.

(note: I can edit attribution if speaker approves)

**Comment by rxgrant** [comment]
A charitable restatement of the 2021 formal objection about interoperability is that in many protocols, after you read one specification you know what to do.  But in this decentralized family of specifications, independent implementations need to read a specification for every DID Method that they handle natively, and the DID-core specification implies trusting a DID Resolver to get DID Documents from DID Methods that are handled using a third party service, instead of handled natively.

What that means is that handling specific DID Methods is a business decision.  In that, it is kind of like pointing your browser to gopher://gopher.quux.org:70/1/ in that leading browsers will not recognize the valid URL and instead point you at search results.  Are these browsers failing to implement a Web standard?  Yes, but they're not confused about it.  Similarly, there will be DID Methods that your browser will not resolve into a DID Document, even with the help of a DID Resolver.  They will not implement the whole family of protocols, and they will not be confused about it.

**Comment by rxgrant** [comment]
The following chart would help visualize these issues.  It would be reasonable to add fields like these to the DID Method registry, or provide a way to focus on which DID Methods have independent evaluations (as might be found in the DID Rubric) informing implementors about the issues:

| DID Method | 2+ separate implementations? | offered in a Resolver (of multiple DID Methods) | offered in a standalone open source library | demonstrated interoperability of verifying key material and endpoint from retrieved DID Document | demonstrated update of key material (using DID Method, not throwing away the DID) | demonstrated revocation of DID |
| --- | --- | --- | --- | --- | --- | --- |
| did:example | yes | yes | yes | yes | yes | yes |

**Comment by pchampin** [comment]
> Maintenance charter for DID-core should explicitly document (...)

Do you mean "it should be documented *in* the charter" (which is how I read your text literally, or "the charter should say that the WG will document it" (which seems more reasonable)?

**Comment by plehegar** [comment]
The charter was [announced ](https://lists.w3.org/Archives/Public/public-did-wg/2024Apr/0000.html)
