### ISSUE TITLE
[wasm] Need more clarity on Component Model

### ISSUE THREAD

**Issue by annevk** [w3c/charter-drafts#441]
https://w3c.github.io/charter-drafts/2023/wasm-wg.html is too vague when it talks about "Component Model". If it means the kind of thing described at https://component-model.bytecodealliance.org/design/why-component-model.html it would help a lot if that was spelled out more explicitly, also for scoping purposes.

cc @sideshowbarker @lukewagner

**Comment by lukewagner** [comment]
If you're interested in the high-level goals/motivation, they are described [here](https://github.com/WebAssembly/component-model/tree/main/design/high-level), in the component-model repo.  And for the concrete proposal (which by now has been mostly implemented, multiple times), the main explainer is [here](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md).
