### ISSUE TITLE
Is this repository monitored?

### ISSUE THREAD

**Issue by annevk** [w3c/charter-drafts#442]
Issues such as https://github.com/w3c/charter-drafts/issues/354 remaining open to this day seem concerning. Draft charters suggest filing feedback here, but who ensures feedback gets resolved?

**Comment by plehegar** [comment]
@annevk , not enough since we missed the service-workers one :(

I did some cleanups nevertheless.

**Comment by annevk** [comment]
Thanks, I guess I know who to ping in the future. :-)
