### ISSUE TITLE
[wg/did] reword charter to not assume a specific browser development process

### ISSUE THREAD

**Issue by pchampin** [w3c/charter-drafts#447]
[[
The following text is problematic, as only some implementers have an "intent to X" process:

> All new features should be supported by at least two intents to implement before being incorporated in the specification.

To resolve this concern, please reword that sentence to not assume a specific browser development process.
]]
From [2023 AC Review](https://www.w3.org/2002/09/wbs/33280/did-wg-2023/results) (member-only)

**Comment by jyasskin** [comment]
This is a duplicate of #436.

**Comment by jyasskin** [comment]
Oh, except it's targeted at the DID charter instead of the charter template. Don't mind me.

**Comment by plehegar** [comment]
The charter was [announced ](https://lists.w3.org/Archives/Public/public-did-wg/2024Apr/0000.html)
