### ISSUE TITLE
[wg/solid] make it clear that the WG will abide by the W3C process

### ISSUE THREAD

**Issue by pchampin** [w3c/charter-drafts#459]
Some reviewers are concerned that the [adopted draft](https://solidproject.org/TR/2022/protocol-20221231) for Solid Protocol v1.0 refers to the [Solid process](https://github.com/solid/process), which is different from the current W3C process. It should therefore be made clear that, by entering the W3C REC track, the deliverable of the WG will be developed entirely under the W3C process.

From https://lists.w3.org/Archives/Public/public-new-work/2023Oct/0007.html
> WG Charter appears to, by reference, setup a BDFL for all Solid related
specifications which is unacceptable. Here's how: Charter Deliverables
(https://www.w3.org/2023/09/proposed-solid-wg-charter.html#deliverables)
links to Solid Protocol, Version 0.10.0
(https://solidproject.org/TR/2022/protocol-20221231) has a Status of This
Document (https://solidproject.org/TR/2022/protocol-20221231#sotd) which
links to Solid process (https://github.com/solid/process) which says "The
following describes how changes to the specifications in the Solid
ecosystem may be proposed and accepted. Anyone may submit a proposal to
alter this process; such proposals will be approved only by Tim
Berners-Lee, who is the Solid Director."

and [other reviews](https://www.w3.org/2002/09/wbs/33280/solid-wg-2023/results#xsupport) (member-visible only)

**Comment by plehegar** [comment]
ALL Working Groups MUST operate under the W3C Process. The W3C Process does give room for Groups to operate but it still must operate under the Process.

**Comment by svgeesus** [comment]
One way forward would be to submit Solid as a Member Submission. That would omit the unhelpful details about a different process, etc. The submission covering letter would indicate a transfer of maintenance to W3C. That submission could then be cited as the adopted draft.

Another option would be for the charter to say "no draft" and for the WG to later resolve to adopt the document referenced above as an ED (under W3C Process of course) and then a FPWD.

**Comment by jyasskin** [comment]
I suggest closing this, since the [replacement charter](https://www.w3.org/2024/07/proposed-linked-web-storage-wg-charter.html) is out for AC review, and the [input document from Solid](https://solidproject.org/ED/protocol) doesn't mention the Solid Process anymore.
