### ISSUE TITLE
[template] TRs produced by the WG will operate strictly under the W3C Process

### ISSUE THREAD

**Issue by csarven** [w3c/charter-drafts#461]
Introduce text to indicate that TRs produced by the WG will operate strictly under the W3C Process.

Yes, it goes without saying that, but as such clarification is requested in https://github.com/w3c/charter-drafts/issues/459 , it should hold true for any charter.

If such text is deemed necessary, the text can be used towards resolving issue 459. If unnecessary, the issue can be closed without changes.

**Comment by plehegar** [comment]
[[
Introduce text to indicate that TRs produced by the WG will operate strictly under the W3C Process.
]]

All Working Groups operate under the W3C Process. So I'm not sure what you're looking for.

**Comment by csarven** [comment]
Right. Am aware.

The question back to you is whether there is a need to say that in a charter (template). See linked issue 459.

**Comment by svgeesus** [comment]
Putting this in the charter template paves the way for some group to say"we follow the W3C process except we ..." which would get flagged at charter review before it went to the AC. So would be a bad thing to do.

> If unnecessary, the issue can be closed without changes.

Closing
