### ISSUE TITLE
[template] Provide text for potential deliverables that might advance from incubation

### ISSUE THREAD

**Issue by jyasskin** [w3c/charter-drafts#472]
Working groups have started adopting the pattern of listing deliverables that they might produce, in addition to the [section in the charter template](https://w3c.github.io/charter-drafts/charter-template.html#normative) that lists specifications they "will deliver". The template should give example text for doing that and any constraints on how precise the description ought to be.

cc/ @tantek

This is related to #262 but doesn't need to be based on a relationship with a specific CG.

**Comment by simoneonofri** [comment]
@jyasskin not from the Charter, but hope it can be useful: draft of the process we're using for FedID CG > FedID WG https://github.com/w3c-fedid/Administration/blob/main/proposals-CG-WG.md

**Comment by svgeesus** [comment]
We now have a [Tentative Deliverables](https://w3c.github.io/charter-drafts/charter-template.html#incubation) section for this purpose.
