### ISSUE TITLE
[wg/did] Authorize the group to work on DID-method-related Notes

### ISSUE THREAD

**Issue by pchampin** [w3c/charter-drafts#473]
From https://lists.w3.org/Archives/Member/member-charters-review/2023Dec/0003.html (member-visible):
> We likewise object to the explicit prohibition of the WG even producing
Notes with respect to DID Method specifications.  This seems explicitly
intended to ensure that there will not be effective interoperability in the
DID space, and I still don't understand how you intend to show effective
interoperability across implementations.  The requirement in Success
Criteria, as I've previously commented on, is a good one, and we are not
demanding that specific DID methods be released from the WG; but it's
concerning to see such antipathy toward standardization of methods, and I'm
not sure that that success criteria will be good enough on its own to prove
effective interop, when it comes time to take another version of the DID
spec to Rec.

This objection was raised on the amended charter proposal following the mediation period:
https://lists.w3.org/Archives/Member/member-charters-review/2023Dec/0000.html (member-visible)

The changes in the amended proposal were introduced to address #431.

**Comment by pchampin** [comment]
It turns out that this objection was not meant as a formal objection.

**Comment by plehegar** [comment]
The charter was [announced ](https://lists.w3.org/Archives/Public/public-did-wg/2024Apr/0000.html)
