### ISSUE TITLE
[wg/did] Do not remove wording about 'seeking consensus'

### ISSUE THREAD

**Issue by pchampin** [w3c/charter-drafts#475]
From https://lists.w3.org/Archives/Member/member-charters-review/2023Dec/0003.html (member-visible):

> I'm particularly concerned to see the removal of the phrase "seek consensus around the best way to achieve effective interoperability" from the introductory paragraph; we believe achieving effective interoperability is critically important to this work overall (indeed, critical to ANY thing striving to be a web standard).  It's not clear to me when this phrase disappeared (before the call held immediately after Thanksgiving, anyway), but we object to the removal of this phrase - the point of creating a web standard should be to encourage, enable and promote interoperability.

This objection was raised on the amended charter proposal following the mediation period:
https://lists.w3.org/Archives/Member/member-charters-review/2023Dec/0000.html (member-visible)

The change occurred in aacf57d , and the removal of the words "seek consensus around the best way to achieve effective interoperability" was only a side-effect of the change of direction taken by the charter. Consequently, PR #474 was proposed to reintroduced these words.

**Comment by pchampin** [comment]
It turns out that this objection was not a formal objection. Furthermore, it was resolved with #474.

**Comment by plehegar** [comment]
The charter was [announced ](https://lists.w3.org/Archives/Public/public-did-wg/2024Apr/0000.html)
