### ISSUE TITLE
[WoT]: W3C WoT WG Charter

### ISSUE THREAD

**Issue by ClaesNilsson** [w3c/charter-drafts#48]
*_Section 1 Scope: *_
- I interpret the figure, which is an example, so that “Thing” in server A exposes a client API making it possible for the script in server A to interact with the Thing in server B. The Thing in server B exposes a server API that makes it possible for the script in server B to expose the resources (sensor and actuator) of this server to other servers and to web browsers. Correct? If so I am suggesting, for clarification reasons, that “client API” and “server API” is added to the figure. The reason is that “Thing” in the figure have different meanings for server A and for server B. In server A “Thing” exposes a client API and in server B “Thing” exposes a server API. So it must be clear in the figure whether “Thing” means a proxy for a thing in another server/device or if Thing represents a server exposing a thing server API.
-  I do not understand the statement under the figure:
  “The proxy on server A could be set up by a script on that server, or by a script on server B.”
  I would instead think that the proxy, i.e. the Thing on server A, is created either as an output of a discovery API provided in server A or by reading a Thing Description from server B.

*_Section 1.2 Scripting APIs: *_
I assume that the APIs standardized are applicable both for User Agents/Browsers as well as for web server applications such as node.js. As W3C traditionally has specified APIs for User Agents this may have to be clarified in the charter. In addition, it may be good to clarify that the scope covers support for a client role interacting with a Thing as well as support for a server role, exposing a Thing. 

Above may be obvious for us in the WoT IG but it may not be obvious for anyone outside of the IG. 

*_Section 1.3 Bindings to Common Protocols: *_
Maybe we could be more tangible here, give some example and clarify what we think should be standardized. I assume that what we want is to define how certain items in the TD is mapped on certain protocols. So, for example, define how an action in the TD is mapped to CoAP POST, an event is mapped to the responses of a CoAP Observe request (or reception of a POST from the other Thing), etc. How far should we go? Only RESTFul protocols or include pub-sub and message oriented protocols such as XMPP and websockets as well?

*_Section 1.4 Out of Scope: *_
I assume that it should be “URI mappings for non-RESTful protocols”, not “URI mappings for non-resourceful protocols”

**Comment by draggett** [comment]
The diagram would get to complicated if we want show all of the APIs, however, from the point of view of an application, it doesn't matter whether the software object is a local thing, or a proxy for a remote thing.

In respect to registration, there are two main possibilities, and I believe that we need both.  One is to create a local proxy for a remote thing. This requires the server to discover the remote server. 

The other approach is to create/publish a remote proxy for a local thing. This requires the server to first discover the remote server. For my C++ server for the Arduino, I use mDNS for that as it is a much better fit than SSDP. For IoT nodes in a sensor network, other approaches will be appropriate.

Re Scripting APIs: The Interest Group has shown an interest in chartering work on the API exposed by the web of things to applications. These are likely to vary somewhat according to the programming language.

Re Bindings to Common Protocols: these define a mapping from the abstract messages in the thing layer to specific protocols and communication patterns at the transfer and transport layers. We will need to standardise metadata for describing what a given server supports.

Re Out of Scope: I would like to hear what our colleagues at Siemens intended with “URI mappings for non-resourceful protocols” as I am unclear as exactly what they meant.

**Comment by mkovatsc** [comment]
After discussion on the mailing list, it turned out to be best to simply drop the point on "URI mappings for non-RESTful protocols".
@h0ru5 Can you confirm?

**Comment by h0ru5** [comment]
First of all thanks for the feedback!
Let me express my opinion for all of @ClaesNilsson 's points:

Ad Sect. 1 / Scope, Motivation: I see also the picture only addressing some specific side-aspects of WoT, yet that is the nature of complex matter: there is not one single image to explain it completely. However, I would like/suggest to also include images from the architecture document.

Ad Sect. 2 / scripting: fully agree. We had some discussion before we had this concept of both server and client-sided scripting APIs in our group as consensus and it might be too implicit here to be understandable by someone not in the discussion.
@ClaesNilsson I think your wording in this issue is covering the matter precisely but understandable, could you send that in as PR?

Ad. Sect 1.3: That is the intention I think. I would see the deliverable as a description how the "patterns" or "interactions"  from the thing description (Actions, properties, events etc.) are mapped into resources and how to interact with these resources.

The question of how these resources and interactions on the resources are then translated in the protocols is sometimes trivial, sometimes more complex. In the end, it only imposes a constraint on the messages used for the sake of better interoperability. For example, its easy for protocols like CoAP or HTTP, but e.g. OFC has defined a mapping of RESTful resources to XMPP. It does not leverage the full power of XMPP, but makes a seamless integration easily possible. 

The tradeoff here is how to use the protocol's intrinisc features to make a mapping "elegant" vs. a simplistic mapping. That's why I see it important for this task to involve the people of the protocol standardization themselves. 

Ad Sect: 1.4 / Out of scope: The meaning of that sentence is clearly too vague at the moment. My longer form of that would be:

>  "We assume the protocols to have some way to uniquely address items (which we call resources) such as actions or properties. This identifier resp. address is an opaque string for in WoT. How this is string is constructed for each individual protocol is not the scope of this group." 

If it is a problem, I have no objection to drop it. The intention was mainly it might however help companies regarding IPR issues.

**Comment by ClaesNilsson** [comment]
Thanks for your replies Dave and Johannes,

Section 1 Scope: Maybe we could add a very simple architecture figure highlighting what we want to standardize?

Section 1.2 Scripting APIs: Yes, I will propose text with a PR.

Section 1.3 Bindings to Common Protocols: The text is currently too vague, and based on your inputs Dave and Johannes I propose the following (but I am not yet ready to submit a PR as I would like to get your response first):

> “To enable interoperability, the Working Group will seek to define standard bindings to common    protocols in close collaboration with the standards development organizations responsible for those protocols. This includes definition of mappings from the "patterns"/”interactions" (actions, properties, events etc.) at the application layer, via abstract messages at the thing layer, to:
> - Transfer layer communication patterns, e.g. push, pull, pub-sub, bi-directional messaging, etc.
> - Specific protocols at the at the transport layer, e.g. REST-based protocols such as HTTP and CoAP, pub-sub-protocols such as MQTT and message-oriented protocols such as XMPP and websockets. Bindings to non-IP transports such as Bluetooth may also be defined. “

(Question: Due to companies IPR-issues, is this too general? Do we, already in the charter have to state exactly for which protocols bindings should be defined?)

(Dave: Could you elaborate on “We will need to standardise metadata for describing what a given server supports.”?)

Section 1.4 Out of Scope: I think that we should drop the statement “URI mappings for non-resourceful protocols” and instead make a clearer definition of the scope for standardization of protocol bindings in section 1.3. I also think that we should drop the statement “Definition of protocol bindings without the collaboration of the standards development organisations responsible for those protocols” and instead make a positive statement in section 1.3. that protocol bindings must be defined with collaboration of the standards development organisations responsible for those protocols.

**Comment by ClaesNilsson** [comment]
Created https://github.com/w3c/charter-drafts/pull/49 for section 1.2 on scripting APIs

**Comment by draggett** [comment]
> On 5 Apr 2016, at 13:10, Claes Nilsson notifications@github.com wrote:
> 
> Thanks for your replies Dave and Johannes,
> 
> Section 1 Scope: Maybe we could add a very simple architecture figure highlighting what we want to standardize?
> 
> I am not against that, but wonder how would it improve on the text description?  What points specifically would you want to make with the figure?
> Section 1.2 Scripting APIs: Yes, I will propose text with a PR.
> 
> Section 1.3 Bindings to Common Protocols: The text is currently too vague, and based on your inputs Dave and Johannes I propose the following (but I am not yet ready to submit a PR as I would like to get your response first):
> 
> “To enable interoperability, the Working Group will seek to define standard bindings to common protocols in close collaboration with the standards development organizations responsible for those protocols. This includes definition of mappings from the "patterns"/”interactions" (actions, properties, events etc.) at the application layer, via abstract messages at the thing layer, to:
> 
> Transfer layer communication patterns, e.g. push, pull, pub-sub, bi-directional messaging, etc.
> Specific protocols at the at the transport layer, e.g. REST-based protocols such as HTTP and CoAP, pub-sub-protocols such as MQTT and message-oriented protocols such as XMPP and websockets. Bindings to non-IP transports such as Bluetooth may also be defined. “
> Sounds clear to me. We could perhaps say ”interactions” rather than “patterns"/”interactions”.
> 
> (Question: Due to companies IPR-issues, is this too general? Do we, already in the charter have to state exactly for which protocols bindings should be defined?)
> 
> My guess is that we don’t need to be that specific, unless we get some clear requests to do so during the AC Review. It would be up to the Working Group to prioritise which protocols they see as the ones to deal with first, and in any case this would be in collaboration with external groups, e.g. IoT alliances that are seeking compatibility with the Web of Things.
> (Dave: Could you elaborate on “We will need to standardise metadata for describing what a given server supports.”?)
> 
> Section 1.4 Out of Scope: I think that we should drop the statement “URI mappings for non-resourceful protocols” and instead make a clearer definition of the scope for standardization of protocol bindings in section 1.3. I also think that we should drop the statement “Definition of protocol bindings without the collaboration of the standards development organisations responsible for those protocols” and instead make a positive statement in section 1.3. that protocol bindings must be defined with collaboration of the standards development organisations responsible for those protocols.
> 
> In principle, an SDO for a given protocol may not be interested in collaborating with the W3C, and may not want to define a binding to the Web of Things.  I don’t believe that the WG Charter should rule such protocols as being out of scope for the Web of Things.

Johannes: perhaps you disagree?  In which case please justify why you feel that way.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub https://github.com/w3c/charter-drafts/issues/48#issuecomment-205772182

—
   Dave Raggett <dsr@w3.org <mailto:dsr@w3.org>>

**Comment by ClaesNilsson** [comment]
According to the WoT-IG TF-AP meeting April 6th I updated the PR https://github.com/w3c/charter-drafts/pull/49 with https://github.com/w3c/charter-drafts/pull/49/commits/efd02460c70bb7cd4f2fd5f78df774c0435e394a.
