### ISSUE TITLE
[wg/svg] CFC period

### ISSUE THREAD

**Issue by fantasai** [w3c/charter-drafts#488]
Minor suggestion...

> A call for consensus (CfC) will be issued for all resolutions (for example, via email, GitHub issue or web-based survey), with a response period from one week to 10 working days, depending on the chair's evaluation of the group consensus on the issue.

Might just want to state a minimum without a maximum. Since we're expecting this group to run pretty slowly, I think it's OK if the chair wants to pick a longer CFC cycle.

**Comment by plehegar** [comment]
Propsoed charter didn't change that (yet?) https://www.w3.org/2024/04/svg-wg.html
