### ISSUE TITLE
[wg/svg] References to Director

### ISSUE THREAD

**Issue by fantasai** [w3c/charter-drafts#489]
> All decisions made by the group should be considered resolved unless and until new information becomes available or unless reopened at the discretion of the Chairs or the Director. 

We don't have a Director anymore. :) Idk what's an appropriate replacement here, maybe the TAG or the Council, or maybe just drop it.

**Comment by plehegar** [comment]
This was addressed. See https://www.w3.org/2024/04/svg-wg.html
