### ISSUE TITLE
[wg/fedid] Proofread the charter draft

### ISSUE THREAD

**Issue by jyasskin** [w3c/charter-drafts#497]
https://w3c.github.io/charter-drafts/2024/wg-fedid.html needs a round of copy-editing. For example, it includes
> Enable federated identity while adhering to [privacy principles](https://www.w3.org/TR/privacy-principles/) despite the [third-party cookies](https://www.w3.org/2001/tag/doc/web-without-3p-cookies/), a cornerstone of such operations, with the FedCM AP

**Comment by simoneonofri** [comment]
fixed by @himorin in this pull request https://github.com/w3c/charter-drafts/pull/498

thank all for the feedback

**Comment by jyasskin** [comment]
"API" isn't the only mistake in just that sentence (e.g. "despite the third-party cookies"), and there are other garbled sentences in the rest of the charter. It actually needs proofreading by a proponent, and not just me trying to point out a few things at a time.

**Comment by simoneonofri** [comment]
hi @jyasskin ok understood. I am going to re-open the issue.
