### ISSUE TITLE
[wg/fedid] Shouldn't there be a liaison with the DID Working Group?

### ISSUE THREAD

**Issue by iherman** [w3c/charter-drafts#499]
I would think a relationship to the [Decentralized Identifier Working Group](https://www.w3.org/2019/did-wg/) is very much relevant...

cc @pchampin @burnburn @brentzundel

**Comment by plehegar** [comment]
DiD seems further away in the satck. Ie, it may be used within the credential format but the Digital Credentials API doesn't dive within the credential.

**Comment by iherman** [comment]
But whatever the API is, it should be usable for DIDs as well. It may be trivial, but I think a liaison with the DID WG to ensure that would still be good.

**Comment by thereisnogabe** [comment]
I agree @iherman I would like to see what we can do to ensure that DIDs are compatible with the APIs defined by the new group.

**Comment by simoneonofri** [comment]
thank you  @iherman and @decentralgabe for your comments. we've been thinking about it, and although it's actually "far away" in terms of the stack as @plehegar correctly says, at the ecosystem level DID is one of the pillars of Decentralized Idenities, so we're working to include it among the liaisons.

skos:related https://github.com/w3c/strategy/issues/450
