### ISSUE TITLE
The figure in section 1 is an inappropriate architecture description

### ISSUE THREAD

**Issue by mjkoster** [w3c/charter-drafts#52]
The figure in section 1, showing an architecture of proxies and scripts, does not seem to be an appropriate summary of the document. It seems to create an architectural context that is misleading with respect to the problems that we are solving. 

Additionally, it seems to imply some architecture constraints that aren't discussed in depth and are not broadly agreed upon. Have we all agreed to implement chains of proxies? What does this architectural constraint induce in the way of desirable properties, and how do we know it doesn't introduce undesirable properties? 

For analysis of architectural styles, constraints, and induced properties, I would follow an approach as laid out in chapter 4 of R. Fielding's dissertation, "Defining the web Architecture: Problems and Insights" at:
http://www.ics.uci.edu/~fielding/pubs/dissertation/web_arch_domain.htm

Overall, I would recommend paying more attention to FIelding and adopting a similar approach to architecture analysis and design.

**Comment by draggett** [comment]
I respectfully disagree. The diagram is not an architecture diagram and  is deliberately very general to avoid being restricted to any one architecture or network topology. It shows how server scripts can be used to define a thing in terms of sensors and actuators. It shows that client scripts can be used to interact with that thing from another device which could be a server or a web browser. In the latter case, a web page script library implements the Web of Things abstraction.  The server script could even run on a web browser. Some people for instance, talk about using the Web of Things between browsers in a peer to peer mode over WebRTC's data channel.

Note that neither the diagram nor the draft charter mention proxy chains. However, it is always the case that you need a proxy for a remote thing if you are to decouple client scripts from the underlying transfer and transport layers. Consider a battery operated device that connects to a local gateway, that in turn connects to a server in a cloud, that in turn exposes the things provided by the original device to other services. This involves a chain with three links.

I've updated the caption for the scripts within the figure to clarify their role which is also indicated by the direction of the arrow, but I guess that that alone was too subtle. The caption for the figure needs updating to make it clear that it is for conceptual purposes and is not intended as an architecture. We can then link to the architecture document for details.

**Comment by ashimura** [comment]
as decided during the Beijing f2f,  this comment is closed
