### ISSUE TITLE
comments from Montreal f2f meeting: "Introduction"

### ISSUE THREAD

**Issue by sebastiankb** [w3c/charter-drafts#54]
Include an introduction section, not only scope at the beginning

**Comment by draggett** [comment]
Now split off, which adds one to the following section numbering.

**Comment by mkovatsc** [comment]
Done in https://w3c.github.io/charter-drafts/wot-wg-2016.html
Please close this issue, since this version was ported to https://github.com/w3c/wot/blob/master/charters/wot-wg-2016.html.

**Comment by sebastiankb** [comment]
as decided in Beijing f2f,  this comment is closed
