### ISSUE TITLE
comments from Montreal f2f meeting: "Figure illustrating"

### ISSUE THREAD

**Issue by sebastiankb** [w3c/charter-drafts#55]
A) wot thing; scenarios were we can use it (3 examples)
B) scenarios: iot platform, discovery, it is not n+1
the interaction of things wether it is in the cloud, GW or even field device

**Comment by draggett** [comment]
Is this something we should have in the charter itself, rather than as a link to the architecture document that is a work item for the Interest Group?

Kaz noted that most charters have relatively short introductions which argues for a link to an external document.

**Comment by sebastiankb** [comment]
as decided in Beijing f2f,  this comment is closed
