### ISSUE TITLE
[ig/security] Coordinate with more W3C groups

### ISSUE THREAD

**Issue by jyasskin** [w3c/charter-drafts#551]
https://w3c.github.io/charter-drafts/2024/ig-security.html#coordination only mentions the WICG and TAG as W3C groups to coordinate with. 

* Coordination with WebAppSec seems important in order to change APIs to systematically patch any holes SING notices.
* Privacy and Security are highly related, so SING and PING/the Privacy WG should keep an eye on eachother's feedback.
* The WICG isn't the only CG that proposes new APIs that need security review early in their lifecycles.

**Comment by simoneonofri** [comment]
Hi @jyasskin, thanks here too. 
Yes it makes sense what you say, I will prepare a PR to update them.
You get the idea of putting the WICG right, you're right surely there are other CGs that then go into Rec Track, maybe I'll specify the issue better. Of course, it's then all about available resources.

**Comment by simoneonofri** [comment]
addressed here, we can follow up the discussion in the PR https://github.com/w3c/strategy/issues/449#issuecomment-2241282461
