### ISSUE TITLE
comments from Montreal f2f meeting: "Building Block Picture"

### ISSUE THREAD

**Issue by sebastiankb** [w3c/charter-drafts#56]
Picture which illustrates the use of TD, Bindings to Protocols and Scripting APIs

**Comment by draggett** [comment]
The existing diagram introduce concepts to supplement the text based explanation. I've now distinguished client and server scripts as this helps with the later text descriptions. The figure caption now makes it clear that this is not an architecture diagram. I've added a link to the IG's architecture document, although currently the link is to the WoT architecture update presented in Montreal, and should be replaced by a link to the HTML document that those slide will become part of.

**Comment by draggett** [comment]
Do we need a building blocks picture and what purpose would it serve?

Presumably this would include the building blocks that correspond to the Working Group's deliverables.

Lacking inspiration, I instead added a box with bullet points that summarise the deliverables.

**Comment by sebastiankb** [comment]
as decided in Beijing f2f,  this comment is closed
