### ISSUE TITLE
[ig/exploration] Comments on draft charter

### ISSUE THREAD

**Issue by michaelchampion** [w3c/charter-drafts#563]
Some comments from reviewing  https://w3c.github.io/charter-drafts/2024/ig-exploration.html and the discussion in https://github.com/w3c/AB-memberonly/issues/207 that led to it:

First, the motivation section lists number of loosely related things. 
* Analyzing new ideas that might impact the web
*  Welcoming new members / community participants
*  Proposing new workshops
*  Monitoring industry trends and what other SDOs are doing about them
* Publishing reports on the results of the various discussions.
* Chartering new groups to formally address the challenges and opportunities identified

A more focused charter would be more likely to be successful. I'd suggest trimming it down to 
* Analyzing new ideas and technologies that might impact the web
*  Monitoring how industry, other  SDOs, and relevant open source projects are responding to those ideas/tech
*  Publishing reports that summarize the trending topic, outline the promise and pitfalls that are being discussed, point to relevant SDO and OSS efforts, and indicate how W3C could engage with the topic.

Many of the other tasks in the existing Motivation section seem more in the domain of the Strategy and Comms teams.   I'd like to see a clearer description of the division of labor between the team and IG on such matters.

Second, all of the above seems more appropriate in the Scope section than the Motivation section. Likewise, the current Scope section, especially the first paragraph, summarizes the Motivation coming out of the AB discussion.

> The goal of Exploration Interest Group provides a platform to help the W3C community explore emerging Web-related technology trends, consider how the community could collaborate to shape these trends for the benefit of the Web users, accelerate chartering investigations and endeavors, and continually strengthen the innovation of W3C.

Third, obviously the charter needs Deliverables and Success Criteria. The more focused scope proposed above suggests the Deliverables are:

1. Creation of a W3C sub-community with the contacts, forums, procedures, and skills needed to monitor and analyze industry trends and what if anything peer organizations are doing about them.
2. Setting up a process to spin up "task forces" (or whatever they might be called) to dig into specific topics as they come up and build (hopefully consensus) analyses of their implications for W3C
3. Reports summarizing the outcome of the analyses and the degree of consensus in the IG, or majority / minority positions on topics that do not get consensus.

Success criteria might be something like "the Team and membership finds the IG discussions and reports valuable in defining, prioritizing, and organizing other W3C outcomes such as workshops, charters, position papers, etc. "

**Comment by dennis-dingwei** [comment]
@michaelchampion thanks Michael for the great comments.  Revised version proposal attached.

**Mission**

The mission of the Exploration Interest Group is to help the W3C community exploring emerging web-related technology trends and consider how the community could collaborate to shape those trends for the benefit of web users.

**Motivation and Background**

The goal of Exploration Interest Group provides a platform to help W3C community investigating emerging technology trends, analyzing their impacts on the evolution of Web technologies, and proposing schemes for W3C to collaborate shaping the trends for the benefit of the Web users. The schemes include organizing Workshops, publishing Reports and creating topic oriented Task Forces etc., assisting the Web community seeking innovative responses to continually strengthen the innovation of W3C and the creativity of Web technologies.

**Scope**

• Monitor industry and technology trends that might impact the web;
• Monitor responses from the industries, SDOs (including W3C CGs, TPAC Breakout sessions, Workshops, Liaison Reports), and Open Source communities on those trends. Work with W3C Team to invite W3C Liaisons to SDOs or other insightful SDOs experts, reporting back on potential areas of investigations;
• Prioritize the trends and propose organizing Workshops, publishing Reports or creating topic oriented Task Forces, for further elaboration;
• Propose chartering potential topics to the Strategy Funnel at the stage of incubation;
• Discuss how to continue improving the exploration and investigation process, proposing improvements to the W3C members and the W3C Team.

**Deliverables**

• Workshops Proposal: propose to organize discussion on relevant topics that need alignment around the next steps for W3C, e.g., "generative AI", "Digital Identity on the Web";

• Reports: Create public analyses of trends that affect the Web, seeking rough consensus or presentation of competing perspectives for a report. The analyses would summarize the trending topic, outline the promise and pitfalls that are being discussed, point to relevant W3C efforts, and indicate the degree of consensus in the group on the value of the topic for the Web;

• Task Forces: Creation of Task Forces as W3C sub-community with the contacts, forums, procedures, and skills needed to dig into specific topics as they come up and build consensus analyses of their implications for W3C.

**Success Criteria**

• W3C Members and the Team finds the Workshop, Reports and the deliverable of the created Task Forces are valuable in defining, prioritizing, and organizing other W3C outcomes such as  position papers and charters, etc.

**Comment by michaelchampion** [comment]
Minor editorial point:
> proposing schemes for W3C to collaborate shaping the trends for the benefit of the Web users. The schemes ...

There might be a better word  or phrase than "schemes" to describe what is being proposed. I hate to say it 😉 but Google's AI answer to the query "scheme synonyms in English" captures my concern:

> Some common synonyms of scheme are design, plan, plot, and project. While all these words mean "a method devised for making or doing something or achieving an end," scheme stresses calculation of the end in view and may **apply to a plan motivated by craftiness and self-interest**

"Procedures", "mechanisms", "work modes", "projects", ... or maybe just "ways" might work better. For example,  " proposing ways for W3C to collaborate on shaping the trends for the benefit of the Web users. These ways of collaborating include organizing Workshops ... "

**Comment by plehegar** [comment]
+1 to use "ways"

**Comment by plehegar** [comment]
I folded the new wording in the draft charter.

I'll also provide separate feedback from in the strategy issue https://github.com/w3c/strategy/issues/451
