### ISSUE TITLE
[wg/fedid] Editorial "To Proposed Recommendation" vs "Beyond Candidate Recommmendation"

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-drafts#566]
The proposed charter uses the following wording:
> In order to advance to Proposed Recommendation, each normative specification is expected to […]

This is perfectly normal and reasonable. However, there are ongoing discussions about potential evolution of the Process which might do away with the existence of Proposed Rec. The following alternative phrasing would mean exactly the same thing, but may be easier to understand in the future if the Process evolves:

> In order to advance beyond Candidate Recommendation, each normative specification is expected to […]

**Comment by simoneonofri** [comment]
Hi @frivoal 

created the PR https://github.com/w3c/charter-drafts/pull/574

feel free to review it

[cc @wseltzer @hlflanagan]

**Comment by simoneonofri** [comment]
closing the issue, we can continue on the PR
