### ISSUE TITLE
comments from Montreal f2f meeting: "Drop Bullet "

### ISSUE THREAD

**Issue by sebastiankb** [w3c/charter-drafts#58]
1.1: drop third bullet

**Comment by draggett** [comment]
Strongly disagree:

The WG should be able to specify normative requirements that enable processing of  metadata on resource constrained devices in an interoperable fashion. Moreover, the binding to RDF is important for scalability. There is a common assumption that JSON-LD or EXI are sufficient, but we should not tie the hands of the WG in that respect. It could well be that the WG opts for a JSON based format. Even if JSON-LD is adopted, there may be a need to specify the default context without burdening resource constrained devices with the need to download and process that context. Some people may want to use an XML based format together with EXI. If we leave serialization formats out scope we will prevent the Working Group from enabling interoperability.

Note that the current practices document defines one such serialization format!

**Comment by sebastiankb** [comment]
Please note, this comment address the bullet "A Linked Data vocabulary for enabling open markets of services, including trust assertions, privacy policies, access control, payments, terms and conditions" in 1.1. which was agreed to remove it.

**Comment by sebastiankb** [comment]
as decided in Beijing f2f,  this comment is closed
