### ISSUE TITLE
PointerEvents: be realistic about TE and PE "reconciling"

### ISSUE THREAD

**Issue by AFBarstow** [w3c/charter-drafts#6]
The draft PtrEvents WG charter says:

[[
This Working Group will reconcile the relationship and best features between these technologies.
]]

The use of "will" here implies the group will be expected to get both the TE and PE communities to agree on a single standard and, unfortunately, that doesn't seem possible, especially since both Apple and Yandex again voiced their disdain for PEs during WebApps 2015-Oct-25 meeting http://www.w3.org/2015/10/26-webapps-minutes.html#item04.

**Comment by plehegar** [comment]
This was removed from the proposed charter.
