### ISSUE TITLE
comments from Montreal f2f meeting: "Life Cycle"

### ISSUE THREAD

**Issue by sebastiankb** [w3c/charter-drafts#60]
in 1.1.: formulate a new bullet point for life cycle;

**Comment by draggett** [comment]
I don't think a separate bullet point is needed.  We can instead simply insert "thing lifecycles" in the first bullet

"A Linked Data vocabulary for describing things in terms of the data and interaction  models they expose to applications. This will cover thing lifecycles, datatypes, ..."

**Comment by mkovatsc** [comment]
(I had this on my action item list.)
I am fine with the current text solution, since it is about at the same complexity as early and late bindings, and it does not need to be highlighted like the security features.

+1 for closing this issue

**Comment by sebastiankb** [comment]
as decided in Beijing f2f,  this comment is closed
