### ISSUE TITLE
[wg/data-shapes] Add text to prepare for spec maintenance.

### ISSUE THREAD

**Issue by afs** [w3c/charter-drafts#619]
Add text to the charter to allow the Data Shapes WG to continue to allow addressing errata and adding [class 4 changes](https://www.w3.org/policies/process/#correction-classes).

**Comment by caribouW3** [comment]
I am not sure what you mean by "continue to allow" here. 
The SHACL Recommendation was published in 2017 when the W3C Process did not allow to make those changes without going back to Candidate Recommendation. Any new version of the specification will have to be published as a draft (FPWD of version next, CRD, etc.) under the current process. Then later on, when it reaches REC, it will be modifiable. Is that what you had in mind?

**Comment by afs** [comment]
Yes - have the WG exist in maintenance new features mode after the spec phase for errata and new features as allowed by W3C Process nowadays.

Is it automatic for working groups? The WG I'm familiar with is RDF-Star WG and I think there is text in the charter that lays the path for this to happen, as well as text in the spec themselves.

https://www.w3.org/2024/10/proposed-rdf-star-wg-charter.html

> The group will then maintain the set of resulting recommendations (RDF 1.2 and SPARQL 1.2).

> The Working Group will also consider [allowing new features](https://www.w3.org/policies/process/#allow-new-features) in these recommendations, according to [Section 6.3.11.4 of the W3C process](https://www.w3.org/policies/process/#revised-rec-features), to ease and speed future evolution.

**Comment by caribouW3** [comment]
Yes, it is automatic. I suppose that the scope in RDF-Star is more precise because it first says it will incorporate specific stuff, then it has this sort of sentence to mean that the group can also decide to maintain and add more later.

Do you think we also need this in the Data Shapes WG charter, or is your concerned already covered by the current Process?

**Comment by afs** [comment]
If it is automatic these days, this issue can be closed as far as I'm concerned.

**Comment by caribouW3** [comment]
thank you
