### ISSUE TITLE
comments from Montreal f2f meeting: "independent of programming languages"

### ISSUE THREAD

**Issue by sebastiankb** [w3c/charter-drafts#62]
1.2: more explanation on independent of programming languages and API to react on life cycle;

**Comment by draggett** [comment]
The current text states "Where practical, APIs will be defined in ways that are independent of the choice of programming languages".  Please propose improved wording!

The current text states "Thing lifecycles, e.g. registering and creating things, either from a thing description or using scripting and enabling applications to be aware of lifecycle transitions". Please propose improved wording!

**Comment by sebastiankb** [comment]
as decided in Beijing f2f,  this comment is closed
