### ISSUE TITLE
comments from Montreal f2f meeting: "Deliverables"

### ISSUE THREAD

**Issue by sebastiankb** [w3c/charter-drafts#65]
- Formulate them refering the scope
- Give date of first public working draft
- Take out here use case&requirements and forward to IG

**Comment by draggett** [comment]
The current draft doesn't list a deliverable for use cases and requirements, so no action on that is needed in the deliverables section.

We need dates for the FPWD, I have put 4 months after charter commencement, but the IG needs to discuss this and see if we can come up with more informed guesses.

The Charter template includes a expectation of the completion date for each deliverable. I have put 22 months after charter commencement, but the IG needs to discuss this and see if we can come up with more informed guesses.

**Comment by sebastiankb** [comment]
as decided in Beijing f2f,  this comment is closed
