### ISSUE TITLE
comments from Montreal f2f meeting: "IG"

### ISSUE THREAD

**Issue by sebastiankb** [w3c/charter-drafts#66]
In 3.1: put intrest group here and talk about the role

**Comment by draggett** [comment]
What are the boundaries of the respect roles of the IG and WG?  We can say that the IG provides a forum for discussion of use cases and requirements, for investigation of areas that need further study before transfer to the standardization track, and for outreach and collaboration with industry alliances and standards development organizations. We can also say that the WG can ask the IG to look into issues that are found to be insufficiently mature for immediate standardization,  Can we also say that the IG will take the lead on work on testing, e.g. preparation of test suites, test frameworks and joint work with other organizations on interoperability testing?

**Comment by sebastiankb** [comment]
as decided in Beijing f2f,  this comment is closed
