### ISSUE TITLE
Web of Things Interest Group Charter

### ISSUE THREAD

**Issue by draggett** [w3c/charter-drafts#67]
This issue is intended to introduce open questions for discussion in respect to the draft charter for the Web of Things Interest Group. This will replace the [old charter](http://www.w3.org/2014/12/wot-ig-charter.html) which expired on 31 March 2016.  We've asked the W3C Management Committee for a short term extension to the old charter to cover the time needed to draft a new charter, reach consensus and drive it through the Advisory Committee review process.

Here are some initial points to seed discussion. Please add further points.
- Do we want to update the introduction to reflect the current positioning of the Web of Things as a suite of inter-platform standards?  For instance, explaining the analogy behind the statement that the Web of Things is to the IoT what the Internet Protocol is to networking. 
- The introduction should set out short, medium and long term priorities for the Interest Group.
- We agree to see through the work items started under the first charter.
- We allow for new work items to be introduced that fit within the charter scope.
- The Interest Group will collaborate with industry alliances and standards development organisations to achieve its goals.
- This collaboration will include joint studies, practical demonstrations that show the technical feasibility of approaches to enabling interoperability across platforms, open source projects, open meetings and so forth.
- The Interest Group will develop materials to assist in outreach in respect to the its goals, and will drive that outreach through a variety of channels.
- The Interest Group will study the challenge of interoperability testing, along with work on test suites and test frameworks
- The goals include building a common understanding around discovery, provisioning, security, resilience, privacy, trust and other requirements for open markets of services.
- The Interest Group will seek to identify work items where there is sufficient maturity and consensus to transfer to the standards track in one or more W3C Working Groups.
- The Interest Group will collaborate with other W3C groups where relevant to its goals.
- The Interest Group will consider initiating new work items at the request of other W3C groups, when these requests fall within the charter scope, and are consistent with Interest Group's priorities.
- How long should we ask for the charter duration?  My feeling is that 12 months is too short, and a longer period would be helpful, as otherwise we will be back working on updating the charter in 10 months time.  We could perhaps ask for a 24 month charter duration.

**Comment by sebastiankb** [comment]
From my point of view, we need a consolidation and we should concentrate on three main agenda points for the IG charter: 
-   New WoT topics and work items that have not been addressed so far (topics should be in disjunction to the WG topics) 
-   Plugfests for evaluation of current work assumptions
-   Supplier and supporter of the WoT WG

The first point should include new use case discussions and identify additional atomic use cases. Technical approaches should be evaluated by organizing plugfests during the f2f meetings. The plugfest should be Current working assumptions should be reflected in a deliverable such as the current practice document.  All this and the experiences should be used as input for the WoT WG.

I agree that 12 months are too short for the charter duration. However, a 24 months period seems too long to me. Is there something in between also possible?

**Comment by takuki** [comment]
Among the list of discussion points Dave created, there are many things that are about how IG will  interact with other groups, and the rest is about defining the product of the IG. 

I drew a chart [https://github.com/takuki/charter-drafts/blob/gh-pages/WoT%20IG%20relationship.png](url) describing the interactions with other groups.

As Sebastian said, I also think two years term is a bit long. 
One idea may be we target TPAC 2017 timeframe to target to try to finish all the work, and discuss further extention at that time if necessary.

By going through Dave's list, I would like to suggest to add the followings to Sebastian's list.

- Drafting and making consensus on WG charter
- Outreach

**Comment by takuki** [comment]
Among the list of discussion points Dave created, there are many things that are about how IG will  interact with other groups, and the rest is about defining the product of the IG. 

I drew a chart [https://github.com/takuki/charter-drafts/blob/gh-pages/WoT IG relationship.png](url) describing the interactions with other groups.

As Sebastian said, I also think two years term is a bit long. 
One idea may be we target TPAC 2017 timeframe to target to try to finish all the work, and discuss further extention at that time if necessary.

By going through Dave's list, I would like to suggest to add the followings to Sebastian's list.

- Drafting and making consensus on WG charter
- Outreach

**Comment by takuki** [comment]
Among the list of discussion points Dave created, there are many things that are about how IG will  interact with other groups, and the rest is about defining the product of the IG. 

I drew a chart describing the interactions with other groups.

https://github.com/takuki/charter-drafts/blob/gh-pages/WoT IG relationship.png

As Sebastian said, I also think two years term is a bit long. 
One idea may be we target TPAC 2017 timeframe to target to try to finish all the work, and discuss further extention at that time if necessary.

By going through Dave's list, I would like to suggest to add the followings to Sebastian's list.

- Drafting and making consensus on WG charter
- Outreach

**Comment by takuki** [comment]
Among the list of discussion points Dave created, there are many things that are about how IG will  interact with other groups, and the rest is about defining the product of the IG. 

I drew a chart describing the interactions with other groups.

https://github.com/takuki/charter-drafts/blob/gh-pages/WoT%20IG%20relationship.png

As Sebastian said, I also think two years term is a bit long. 
One idea may be we target TPAC 2017 timeframe to target to try to finish all the work, and discuss further extention at that time if necessary.

By going through Dave's list, I would like to suggest to add the followings to Sebastian's list.
- Drafting and making consensus on WG charter
- Outreach

**Comment by sebastiankb** [comment]
why is a new issue thread opened with the same name? Where should I now comment on?

**Comment by mkovatsc** [comment]
This is due to moving from w3c/draft-charters to the w3c/wot repository.
We can close the issue here.

**Comment by sebastiankb** [comment]
ok for me

**Comment by draggett** [comment]
Closing this issue - please continue the discussion at https://github.com/w3c/wot/issues
