### ISSUE TITLE
WoT WG coordination with external organizations?

### ISSUE THREAD

**Issue by draggett** [w3c/charter-drafts#68]
What should the Web of Things WG charter say in respect to coordination with external organizations? Is it okay for this coordination to be driven by the Web of Things Interest Group?

**Comment by ClaesNilsson** [comment]
Not quite I think. Section 2.3 "Bindings to Common Platforms and Protocols" states:
"the Working Group will seek to define standard bindings to common platforms and protocols in close collaboration with the industry alliances and standards development organizations responsible for these". That indicates that collaboration must be performed for the detailed specification work performed in the WG.

For example, collaboration with IETF is essential. In Montreal we also discussed bindings to existing platforms such as OCF, oneM2M and Smartthings but I am not sure if these organizations should be listed. Maybe also collaboration with OMA for LWM2M is relevant?

**Comment by draggett** [comment]
Including a list of organisations is valuable, but also problematic as the list is likely to change over the charter period. For example, an agreement with the OPC Foundation was inked at this week's Hannover Fair.

**Comment by draggett** [comment]
We've moved the charter to the WoT IG repository will track issues there.
