### ISSUE TITLE
[WoT] Thing Description support for streams

### ISSUE THREAD

**Issue by mkovatsc** [w3c/charter-drafts#72]
2.1 of the charter says "including streams". This is already a very specific solution for an at the moment undefined/unmentioned problem. The problem I see is the support for time series. While streams can be a solution for that, most IoT protocols do not have support for this. Furthermore, we currently have no current practices for streaming, and hence no evaluation of its feasibility.

Proposal: replace "including streams" with "time series" in the charter.

**Comment by draggett** [comment]
I would prefer to stick with streams and explain it better.  In particular, a stream is an interface for interacting with a time sequence of values.

I don't see why you say that most IoT protocols do not have support for streams.  It looks like you are confusing the API exposed to applications with the communication patterns used with particular protocols.  For the data model, we need a streams interface. 

For the transport layer, the approach depends on the context.  CoAP, for instance supports the pub/sub pattern with OBSERVE.  For HTTP, you could push successive samples over the same connection or you could make separate HTTP connections for each sample.  In some case, samples from multiple sensors need to be collected, buffered and sent en masse for efficient use of networks and for long battery life.

There is plenty of work on stream interfaces and there is a clear requirement for this capability, so it needs to be part of the WG charter scope, even though we haven't elaborated the details yet. I posted ideas on this many months ago.

**Comment by draggett** [comment]
Note that this issue is closed as we're moving the discussion to https://github.com/w3c/wot/issues
