### ISSUE TITLE
Previous charters

### ISSUE THREAD

**Issue by svgeesus** [w3c/charter-drafts#82]
In the template, there is a section called **Charter History**, but with a note that this section is solely for charter _extensions_. However, it is at least customary to include a link to the previous charter, when rechartered rather than just extended.

I suggest fixing this by making the history section apply to both rechartering and extension (so it would not be included in a brand new charter). Add a todo paragraph saying "keep one of these". Keep the existing history table, as one option, and add a paragraph with a link to the previous charter, as a second option.

**Comment by svgeesus** [comment]
Actually I see the table does have entries for rechartered, so it is the introductory text which is incorrect

**Comment by svgeesus** [comment]
Suggested fix is https://github.com/w3c/charter-drafts/pull/83

**Comment by wseltzer** [comment]
That's been merged, closing.
