### ISSUE TITLE
.todo colors

### ISSUE THREAD

**Issue by shawna-slh** [w3c/charter-drafts#93]
https://www.w3.org/2006/02/charter-style.css

> .todo
>  {
>   background-color:yellow;
> }

and /charter-drafts/charter-template.html

> .todo {
>         color: red;
>       }

make for difficult and uncomfortable reading. The yellow is too bright and the contrast ratio is only 3.97:1. (for more info: [Perspectives](https://www.w3.org/WAI/perspectives/contrast.html), [Easy Checks](https://www.w3.org/WAI/eval/preliminary#contrast), [WCAG](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast7.html))

I suggest something more like:

> color: #900
> background-color:#FFC

is easier on sensitive eyes and contrast ratio of 8.7:1.

**Comment by koalie** [comment]
Thank you, Shawn! Done in github for the template, and elsewhere for the style sheet:
[[/w3ccvs/WWW/2006/02/charter-style.css,v  <--  WWW/2006/02/charter-style.css
new revision: 1.39; previous revision: 1.38]]
