### ISSUE TITLE
"charter approval" should be "call for participation"

### ISSUE THREAD

**Issue by tidoust** [w3c/charter-drafts#96]
A comment raised during the call for review for the renewal of the Second Screen Working Group: in section 2, "at the time of charter approval" is better expressed as "at the time of the call for participation" because it is the formal notice of approval and initiation.

See comment in (member-only link):
https://lists.w3.org/Archives/Member/w3c-archive/2016Oct/0434.html

**Comment by svgeesus** [comment]
Fixed, see https://github.com/w3c/charter-drafts/blob/gh-pages/charter-template.html#L87
