### ISSUE TITLE
"half of a day" should be "half a working day"

### ISSUE THREAD

**Issue by tidoust** [w3c/charter-drafts#97]
A comment raised during the call for review for the renewal of the Second Screen Working Group: in section 4, "half of a day" is ambiguous because it could mean 12 hours. Suggestion is to use "half a working day".

See comment in (member-only link):
https://lists.w3.org/Archives/Member/w3c-archive/2016Oct/0434.html

**Comment by svgeesus** [comment]
Fixed by https://github.com/w3c/charter-drafts/commit/b6dda85a564077c11ef905f54b39aa3e315e8c03
